// Physical domain tables. Every observation also carries the common provenance columns.
// n = identifier/text, x = unbounded text, i = integer, b = nullable boolean, d = digest.
export const MODEL = {
  capability: { container_capability_id:'n', name:'n', version:'n', root_scenario_id:'n', experience_id:'n', lifecycle:'n' },
  feature: { name:'x', language:'n', description:'x', scenario_count:'i' },
  scenario: { scenario_id:'n', name:'x', terminal:'b', input_id:'n', input_contract_id:'n', event_id:'n', execution_authority_id:'n', outcome_id:'n', outcome_contract_id:'n', variant_count:'i', observable_condition_count:'i' },
  input: { input_id:'n', scenario_id:'n', contract_id:'n' },
  event: { event_id:'n', scenario_id:'n', execution_authority_id:'n' },
  outcome: { outcome_id:'n', scenario_id:'n', contract_id:'n', terminal:'b', variant_id:'n', observable_condition_count:'i' },
  product: { product_id:'n', scenario_id:'n', contract_id:'n', product_role:'n' },
  contract: { contract_id:'n', schema_ref:'x' },
  schema: { schema_id:'x', dialect:'x', title:'x', declared_type:'n' },
  blueprint_node: { node_id:'n', kind:'n', altitude:'n', ordinal:'i' },
  blueprint_edge: { edge_id:'n', from_id:'n', to_id:'n', topology:'n', variant_id:'n' },
  observed_blueprint_route: { edge_id:'n', from_id:'n', to_id:'n', topology:'n', variant_id:'n' },
  observed_semantic_graph_transition: { transition_id:'n', from_scenario_id:'n', to_scenario_id:'n', from_outcome_id:'n', to_input_id:'n', topology:'n', variant_id:'n' },
  observed_execution_invoke_scenario: { operation_id:'n', from_scenario_id:'n', to_scenario_id:'n', execution_authority_id:'n' },
  observed_runtime_route: { edge_id:'n', from_id:'n', to_id:'n', kind:'n', altitude:'n' },
  execution_authority: { execution_authority_id:'n', scenario_id:'n', operation_count:'i' },
  operation: { operation_id:'n', ordinal:'i', scenario_id:'n', execution_authority_id:'n', kind:'n', port_id:'n', target_scenario_id:'n', mechanic_binding_id:'n', structural_digest:'d' },
  transformation: { transformation_id:'n', expression_digest:'d' },
  mechanic: { mechanic_id:'n', binding_id:'n', mechanic_type:'n', provider_id:'n', provider_name:'x', implementation_ref:'x', configuration_digest:'d' },
  port: { port_id:'n', provider_id:'n', transformation_id:'n', binding_kind:'n' },
  provider_slot: { slot_id:'n', cell_id:'n', port_id:'n', mechanic_id:'n', declared_provider_id:'n', profile_constraints:'x' },
  provider: { provider_id:'n', authority_id:'n', lifecycle:'n', responsibility:'x' },
  external_provider: { provider_id:'n', name:'x' },
  external_provider_capability: { provider_id:'n', bound_capability_id:'n', verb:'n', object:'n' },
  provider_binding: { binding_id:'n', binding_kind:'n', slot_id:'n', cell_id:'n', port_id:'n', mechanic_id:'n', provider_id:'n', provider_digest:'x', implementation_ref:'x', binding_digest:'d' },
  interface: { interface_id:'n', kind:'n', root_scenario_id:'n', target_capability_id:'n' },
  fixture: { fixture_id:'n', terminal_scenario_id:'n', expected_disposition:'n', assertion_count:'i' },
  fixture_scenario: { fixture_id:'n', scenario_id:'n', ordinal:'i' },
  fixture_assertion: { fixture_id:'n', ordinal:'i', condition_id:'n', assertion_path:'x', operator:'n', value_json:'x', target_scenario_id:'n' },
  proof_obligation: { obligation_id:'n', kind:'n', status:'n', subject_id:'n' },
  evidence: { evidence_id:'n', evidence_digest:'d', kind:'n', disposition:'n', declared_digest:'x', subject_id:'n' },
  projection_authority: { projection_authority_id:'n', kind:'n', input_contract_id:'n', output_contract_id:'n' },
  dependency: { target_capability_id:'n', target_version:'n', target_digest:'x', binding_ref:'x', binding_digest:'d', dependency_kind:'n' },
  semantic_term: { term_id:'n', label:'x', normalized_label:'x', definition:'x', vocabulary_kind:'n' },
  term_relationship: { relationship_id:'n', from_term_id:'n', to_term_id:'n', kind:'n' },
  classification: { subject_id:'n', classification:'n', classified_kind:'n' },
  fact: { fact_id:'n', subject_id:'n', predicate:'n', object_id:'n', value_json:'x' },
  fact_relationship: { relationship_id:'n', from_fact_id:'n', to_fact_id:'n', kind:'n' },
  semantic_object: { semantic_object_id:'n', canonical_id:'n', kind:'n' },
  semantic_object_relationship: { relationship_id:'n', from_semantic_object_id:'n', to_semantic_object_id:'n', kind:'n' },
  precedent: { precedent_id:'n', subject_id:'n', kind:'n' },
  pattern_candidate: { pattern_id:'n', kind:'n', status:'n' },
  extraction_issue: { code:'n', detail:'x', severity:'n' }
};
export const commonColumns = {
  row_id:'d', artifact_id:'d', capability_id:'n', is_primary:'b', origin_layer:'n',
  source_pointer:'x', pointer_kind:'n', derivation_rule:'n', object_digest:'d', payload_json:'x'
};
