import { createHash } from 'node:crypto';

export const tables = new Map();
export const q = name => '[' + name.replaceAll(']', ']]') + ']';
export const fq = name => name.split('.').map(q).join('.');
export const digest = text => createHash('sha256').update(text).digest('hex');
const types = {K:'bigint',D:'binary(32)',ID:'nvarchar(400) COLLATE Latin1_General_100_BIN2',CODE:'varchar(64) COLLATE Latin1_General_100_BIN2',TXT:'nvarchar(max)',PTR:'nvarchar(400) COLLATE Latin1_General_100_BIN2',N:'int',B:'bit',T:'datetime2(7)',BYTES:'varbinary(max)'};
const list = x => Array.isArray(x) ? x : x.split(',');
export function table(name, columns, pk, options={}) {
  if(!name.includes('.')) name='model.'+name;
  if(tables.has(name)) throw new Error('DUPLICATE_TABLE:'+name);
  const t={name,columns:{},pk:list(pk),identity:options.identity!==false,aks:[],fks:[],checks:[],filtered:[],indexes:[],owner:null,kind:null};
  t.col=(name,type)=>{const nullable=type.endsWith('?');type=nullable?type.slice(0,-1):type;t.columns[name]={type:types[type]??type,token:type,nullable};return t;};
  t.ak=(cols)=>{cols=list(cols);if(![t.pk,...t.aks].some(a=>a.join()==cols.join()))t.aks.push(cols);return t;};
  t.fk=(cols,target,targetCols)=>{target=target.includes('.')?target:'model.'+target;t.fks.push({cols:list(cols),target,targetCols:list(targetCols??target.split('.').at(-1)+'_pk')});return t;};
  t.ck=sql=>{t.checks.push(sql);return t;};
  t.ux=(cols,where)=>{t.filtered.push({cols:list(cols),where});return t;};
  t.ix=cols=>{t.indexes.push(list(cols));return t;};
  t.lineage=(ownerColumn,parentTable,parentDefinitionColumn='semantic_object_definition_pk')=>{
    t.col('_owner_definition_pk','K').col('_canonical_pointer','PTR');
    t.fk('_owner_definition_pk','semantic_object_definition');
    t.owner=ownerColumn?{column:ownerColumn,parent:parentTable?.includes('.')?parentTable:'model.'+parentTable,target:parentDefinitionColumn}: {self:true};
    return t;
  };
  for(const [c,type] of Object.entries(columns))t.col(c,type);
  tables.set(name,t); return t;
}
const T=table;
export const fixed=(t,col,value)=>t.col(col,'CODE').ck(`${q(col)}='${value}'`);
export const enumCheck=(t,col,values,nullable=false)=>t.ck(`${nullable?`${q(col)} IS NULL OR `:''}${q(col)} IN (${values.map(v=>`'${v}'`).join(',')})`);
export const refState=(t,col,state)=>{
  t.col(state,'CODE');enumCheck(t,state,['RESOLVED','ABSENT','EXPLICIT_NULL','UNRESOLVED','NOT_APPLICABLE']);
  t.ck(`(${q(state)}='RESOLVED' AND ${q(col)} IS NOT NULL) OR (${q(state)}<>'RESOLVED' AND ${q(col)} IS NULL)`);return t;
};
export const pairs=(t,a,b)=>t.ck(`(${q(a)} IS NULL AND ${q(b)} IS NULL) OR (${q(a)} IS NOT NULL AND ${q(b)} IS NOT NULL)`);

T('source.estate_snapshot',{estate_snapshot_pk:'K',snapshot_digest:'D',estate_manifest_digest:'D',source_head:'ID?',captured_at:'T?'},'estate_snapshot_pk').ak('snapshot_digest');
T('source.content_object',{content_object_pk:'K',content_digest:'D',content_bytes:'BYTES',byte_length:'bigint'},'content_object_pk').ak('content_digest').ck('byte_length>=0 AND byte_length=DATALENGTH(content_bytes)').ck("content_digest=HASHBYTES('SHA2_256',content_bytes)");
T('source.source_appearance',{source_appearance_pk:'K',estate_snapshot_pk:'K',content_object_pk:'K',appearance_digest:'D',source_path:'TXT',source_class:'CODE',container_locator:'TXT?',capsule_digest:'D?',referenced_authority_digest:'D?',entry_id:'ID?'},'source_appearance_pk').ak('estate_snapshot_pk,appearance_digest').fk('estate_snapshot_pk','source.estate_snapshot').fk('content_object_pk','source.content_object');
T('source.mapping_rule',{mapping_rule_pk:'K',rule_id:'ID',rule_digest:'D',source_profile:'ID',rule_content_object_pk:'K',canonicalization_profile:'ID'},'mapping_rule_pk').ak('rule_id,rule_digest').fk('rule_content_object_pk','source.content_object');
enumCheck(T('source.source_classification',{source_appearance_pk:'K',mapping_rule_pk:'K',family_code:'CODE',classification_state:'CODE'},'source_appearance_pk,mapping_rule_pk,family_code',{identity:false}).fk('source_appearance_pk','source.source_appearance').fk('mapping_rule_pk','source.mapping_rule'),'classification_state',['SUPPORTED','UNSUPPORTED','AMBIGUOUS','OUTSIDE_SCOPE']);
T('source.namespace_mapping',{mapping_rule_pk:'K',object_kind:'CODE',source_scope:'ID',namespace_pk:'K'},'mapping_rule_pk,object_kind,source_scope',{identity:false}).fk('mapping_rule_pk','source.mapping_rule').fk('namespace_pk','identity_namespace','namespace_pk');
enumCheck(T('source.source_observation',{source_observation_pk:'K',source_appearance_pk:'K',locator:'TXT',locator_digest:'D',observation_kind:'CODE',presence_state:'CODE',observed_value_content_pk:'K?'},'source_observation_pk').ak('source_appearance_pk,locator_digest,observation_kind').ak('source_observation_pk,observation_kind').fk('source_appearance_pk','source.source_appearance').fk('observed_value_content_pk','source.content_object'),'presence_state',['PRESENT','ABSENT','EXPLICIT_NULL','NOT_APPLICABLE']);
fixed(T('source.declaration_observation',{source_observation_pk:'K',declared_kind:'CODE',declared_id:'TXT?',namespace_text:'TXT?'},'source_observation_pk',{identity:false}),'observation_kind','DECLARATION').fk('source_observation_pk,observation_kind','source.source_observation','source_observation_pk,observation_kind');
fixed(T('source.relationship_observation',{source_observation_pk:'K',relationship_kind:'CODE',source_reference:'TXT?',target_reference:'TXT?',declared_target_digest:'D?'},'source_observation_pk',{identity:false}),'observation_kind','RELATIONSHIP').fk('source_observation_pk,observation_kind','source.source_observation','source_observation_pk,observation_kind');
T('source.source_lineage',{source_lineage_pk:'K',semantic_object_definition_pk:'K',member_kind:'CODE',canonical_pointer:'PTR',source_observation_pk:'K',mapping_rule_pk:'K',contribution_role:'CODE'},'source_lineage_pk').ak('semantic_object_definition_pk,member_kind,canonical_pointer,source_observation_pk,mapping_rule_pk,contribution_role').fk('semantic_object_definition_pk','semantic_object_definition').fk('source_observation_pk','source.source_observation').fk('mapping_rule_pk','source.mapping_rule');
enumCheck(T('source.estate_model',{estate_model_pk:'K',estate_snapshot_pk:'K',mapping_manifest_digest:'D',publication_state:'CODE'},'estate_model_pk').ak('estate_snapshot_pk,mapping_manifest_digest').fk('estate_snapshot_pk','source.estate_snapshot'),'publication_state',['BUILDING','PUBLISHED','FAILED']);
T('source.estate_model_rule',{estate_model_pk:'K',mapping_rule_pk:'K'},'estate_model_pk,mapping_rule_pk',{identity:false}).fk('estate_model_pk','source.estate_model').fk('mapping_rule_pk','source.mapping_rule');
T('source.current_model',{singleton_id:'tinyint',estate_model_pk:'K'},'singleton_id',{identity:false}).ck('singleton_id=1').fk('estate_model_pk','source.estate_model');
T('identity_namespace',{namespace_pk:'K',namespace_kind:'CODE',namespace_id:'ID'},'namespace_pk').ak('namespace_kind,namespace_id');
T('namespace_owner',{namespace_pk:'K',owner_semantic_object_pk:'K',scope_kind:'CODE'},'namespace_pk',{identity:false}).fk('namespace_pk','identity_namespace','namespace_pk').fk('owner_semantic_object_pk','semantic_object').ak('owner_semantic_object_pk,scope_kind');
T('semantic_object',{semantic_object_pk:'K',object_kind:'CODE',namespace_pk:'K',declared_id:'ID'},'semantic_object_pk').ak('namespace_pk,declared_id').ak('semantic_object_pk,object_kind,namespace_pk,declared_id').ak('semantic_object_pk,object_kind').fk('namespace_pk','identity_namespace','namespace_pk');
T('semantic_object_definition',{semantic_object_definition_pk:'K',semantic_object_pk:'K',object_kind:'CODE',definition_digest:'D',canonical_content_pk:'K'},'semantic_object_definition_pk').ak('semantic_object_pk,definition_digest').ak('semantic_object_definition_pk,semantic_object_pk,object_kind,definition_digest').ak('semantic_object_definition_pk,semantic_object_pk,definition_digest').ak('semantic_object_definition_pk,object_kind').fk('semantic_object_pk,object_kind','semantic_object','semantic_object_pk,object_kind').fk('canonical_content_pk','source.content_object');
T('definition_version_label',{semantic_object_pk:'K',version_label:'ID',semantic_object_definition_pk:'K',definition_digest:'D'},'semantic_object_pk,version_label',{identity:false}).fk('semantic_object_definition_pk,semantic_object_pk,definition_digest','semantic_object_definition','semantic_object_definition_pk,semantic_object_pk,definition_digest').lineage();
T('estate_definition',{estate_model_pk:'K',semantic_object_definition_pk:'K'},'estate_model_pk,semantic_object_definition_pk',{identity:false}).fk('estate_model_pk','source.estate_model').fk('semantic_object_definition_pk','semantic_object_definition');
T('estate_capability',{estate_model_pk:'K',capability_pk:'K',capability_version_pk:'K',semantic_object_definition_pk:'K'},'estate_model_pk,capability_pk',{identity:false}).fk('estate_model_pk,semantic_object_definition_pk','estate_definition','estate_model_pk,semantic_object_definition_pk').fk('capability_pk,capability_version_pk','capability_version','capability_pk,capability_version_pk').fk('capability_version_pk,semantic_object_definition_pk','capability_version','capability_version_pk,semantic_object_definition_pk');

export const families=[];
export function identity(name,version,kind,idColumn=name+'_id',extra={}) {
  const t=fixed(T(name,{[name+'_pk']:'K',namespace_pk:'K',[idColumn]:'ID',semantic_object_pk:'K'},name+'_pk'),'object_kind',kind);
  t.ak('namespace_pk,'+idColumn).ak('semantic_object_pk').ak(name+'_pk,semantic_object_pk').fk('namespace_pk','identity_namespace','namespace_pk').fk(['semantic_object_pk','object_kind','namespace_pk',idColumn],'semantic_object','semantic_object_pk,object_kind,namespace_pk,declared_id');
  const v=fixed(T(version,{[version+'_pk']:'K',[name+'_pk']:'K',semantic_object_pk:'K',semantic_object_definition_pk:'K',definition_digest:'D',...extra},version+'_pk'),'object_kind',kind);
  v.ak(name+'_pk,definition_digest').ak('semantic_object_definition_pk').ak(name+'_pk,'+version+'_pk').ak(version+'_pk,semantic_object_definition_pk').fk(name+'_pk,semantic_object_pk',name,name+'_pk,semantic_object_pk').fk('semantic_object_definition_pk,semantic_object_pk,object_kind,definition_digest','semantic_object_definition','semantic_object_definition_pk,semantic_object_pk,object_kind,definition_digest').lineage();
  t.kind=kind;v.kind=kind;families.push({name,version,kind,idColumn});return [t,v];
}
identity('capability','capability_version','CAPABILITY','capability_id',{name:'TXT',actor:'TXT?',intent:'TXT?',outcome:'TXT?',experience_id:'ID?',experience_actor:'TXT?',experience_promise:'TXT?'});
refState(identity('product','product_definition','PRODUCT','product_id',{name:'TXT',contract_version_pk:'K?'})[1].fk('contract_version_pk','contract_version'),'contract_version_pk','contract_reference_state');
refState(identity('contract','contract_version','CONTRACT','contract_id',{name:'TXT?',contract_kind:'CODE?',schema_object_pk:'K?'})[1].fk('schema_object_pk','schema_object'),'schema_object_pk','schema_reference_state');
identity('execution_authority','execution_authority_version','EXECUTION_AUTHORITY','execution_authority_id',{authority_profile:'ID'});
identity('transformation','transformation_version','TRANSFORMATION','transformation_id',{expression_profile:'ID'});
identity('mechanic','mechanic_version','MECHANIC','mechanic_id',{name:'TXT?',mechanic_kind:'CODE?',definition_profile:'ID'});
identity('port','port_version','PORT','port_id',{name:'TXT?',port_profile:'ID'});
identity('provider','provider_definition','PROVIDER','provider_id',{name:'TXT?',declaration_profile:'ID'});
identity('provider_profile','provider_profile_version','PROVIDER_PROFILE','provider_profile_id',{profile_name:'TXT?',profile_authority:'ID'});
identity('blueprint','blueprint_version','BLUEPRINT','blueprint_id',{capability_pk:'K',capability_version_pk:'K',carrier_profile:'ID',source_disposition:'CODE'})[1].fk('capability_pk,capability_version_pk','capability_version','capability_pk,capability_version_pk');
identity('authority','authority_definition','AUTHORITY','authority_id',{authority_kind:'CODE',authority_profile:'ID'});
const [sc,sv]=identity('scenario','scenario_version','SCENARIO','scenario_id',{name:'TXT',source_profile:'ID'});
sc.col('capability_pk','K').fk('capability_pk','capability').ak('capability_pk,scenario_id').ak('capability_pk,scenario_pk');
T('capability_scenario',{capability_pk:'K',capability_version_pk:'K',scenario_pk:'K',scenario_version_pk:'K'},'capability_version_pk,scenario_pk',{identity:false}).ak('capability_version_pk,scenario_version_pk').fk('capability_pk,capability_version_pk','capability_version','capability_pk,capability_version_pk').fk('capability_pk,scenario_pk','scenario','capability_pk,scenario_pk').fk('scenario_pk,scenario_version_pk','scenario_version','scenario_pk,scenario_version_pk').lineage('capability_version_pk','capability_version');
T('capability_root_scenario',{capability_version_pk:'K',scenario_pk:'K'},'capability_version_pk',{identity:false}).fk('capability_version_pk,scenario_pk','capability_scenario','capability_version_pk,scenario_pk').lineage('capability_version_pk','capability_version');
export const owned=[];
export function address(t,kind,idColumn) {
  t.col('semantic_object_pk','K').col('semantic_object_definition_pk','K').col('namespace_pk','K').col('definition_digest','D');fixed(t,'object_kind',kind);
  t.ak('semantic_object_definition_pk').fk(['semantic_object_pk','object_kind','namespace_pk',idColumn],'semantic_object','semantic_object_pk,object_kind,namespace_pk,declared_id').fk('semantic_object_definition_pk,semantic_object_pk,object_kind,definition_digest','semantic_object_definition','semantic_object_definition_pk,semantic_object_pk,object_kind,definition_digest').lineage();t.kind=kind;owned.push({table:t.name,kind,idColumn});return t;
}
refState(address(T('scenario_input',{scenario_version_pk:'K',input_id:'ID',name:'TXT?',input_contract_version_pk:'K?'},'scenario_version_pk',{identity:false}).fk('scenario_version_pk','scenario_version').fk('input_contract_version_pk','contract_version'),'SCENARIO_INPUT','input_id'),'input_contract_version_pk','contract_reference_state');
refState(address(T('scenario_event',{scenario_version_pk:'K',event_id:'ID',name:'TXT?',responsibility:'TXT',execution_authority_version_pk:'K?'},'scenario_version_pk',{identity:false}).fk('scenario_version_pk','scenario_version').fk('execution_authority_version_pk','execution_authority_version'),'SCENARIO_EVENT','event_id'),'execution_authority_version_pk','authority_reference_state');
address(T('scenario_outcome',{scenario_version_pk:'K',outcome_id:'ID',name:'TXT?',experience:'TXT',terminal:'B?',terminal_disposition:'ID?'},'scenario_version_pk',{identity:false}).fk('scenario_version_pk','scenario_version'),'SCENARIO_OUTCOME','outcome_id');
T('outcome_variant',{outcome_variant_pk:'K',scenario_version_pk:'K',variant_id:'ID',terminal:'B?'},'outcome_variant_pk').ak('scenario_version_pk,variant_id').ak('scenario_version_pk,outcome_variant_pk').fk('scenario_version_pk','scenario_outcome','scenario_version_pk').lineage('scenario_version_pk','scenario_version');
T('outcome_product',{scenario_version_pk:'K',product_definition_pk:'K'},'scenario_version_pk,product_definition_pk',{identity:false}).fk('scenario_version_pk','scenario_outcome','scenario_version_pk').fk('product_definition_pk','product_definition').lineage('scenario_version_pk','scenario_version');
T('outcome_variant_product',{outcome_variant_pk:'K',product_definition_pk:'K'},'outcome_variant_pk,product_definition_pk',{identity:false}).fk('outcome_variant_pk','outcome_variant').fk('product_definition_pk','product_definition').lineage('outcome_variant_pk','outcome_variant','_owner_definition_pk');
T('scenario_outcome_contract',{scenario_version_pk:'K',contract_version_pk:'K'},'scenario_version_pk',{identity:false}).fk('scenario_version_pk','scenario_outcome','scenario_version_pk').fk('contract_version_pk','contract_version').lineage('scenario_version_pk','scenario_version');
T('schema_object',{schema_object_pk:'K',content_digest:'D',dialect:'ID?',content_object_pk:'K'},'schema_object_pk').ak('content_digest').ak('content_object_pk').fk('content_object_pk','source.content_object');
T('port_contract',{port_version_pk:'K',direction:'CODE',member_ordinal:'N',role:'ID?',contract_version_pk:'K'},'port_version_pk,direction,member_ordinal',{identity:false}).fk('port_version_pk','port_version').fk('contract_version_pk','contract_version').ux('port_version_pk,direction,role','role IS NOT NULL').lineage('port_version_pk','port_version');

T('execution_operation',{execution_operation_pk:'K',execution_authority_version_pk:'K',operation_id:'ID?',ordinal:'N',operation_kind:'CODE'},'execution_operation_pk').ak('execution_authority_version_pk,ordinal').ak('execution_authority_version_pk,execution_operation_pk').ak('execution_operation_pk,operation_kind').ux('execution_authority_version_pk,operation_id','operation_id IS NOT NULL').fk('execution_authority_version_pk','execution_authority_version').lineage('execution_authority_version_pk','execution_authority_version');
for(const [suffix,kind,target,column] of [['port_invocation','invoke-port','port_version','port_version_pk'],['scenario_invocation','invoke-scenario','scenario_version','target_scenario_version_pk'],['state_projection','project-state','transformation_version','transformation_version_pk']]){
  fixed(T('operation_'+suffix,{execution_operation_pk:'K',[column]:'K'},'execution_operation_pk',{identity:false}),'operation_kind',kind).fk('execution_operation_pk,operation_kind','execution_operation','execution_operation_pk,operation_kind').fk(column,target).lineage('execution_operation_pk','execution_operation','_owner_definition_pk');
}
T('operation_mechanic',{execution_operation_pk:'K',mechanic_version_pk:'K',role:'CODE'},'execution_operation_pk,mechanic_version_pk,role',{identity:false}).fk('execution_operation_pk','execution_operation').fk('mechanic_version_pk','mechanic_version').lineage('execution_operation_pk','execution_operation','_owner_definition_pk');
T('operation_predecessor',{execution_authority_version_pk:'K',execution_operation_pk:'K',predecessor_operation_pk:'K'},'execution_operation_pk,predecessor_operation_pk',{identity:false}).fk('execution_authority_version_pk,execution_operation_pk','execution_operation','execution_authority_version_pk,execution_operation_pk').fk('execution_authority_version_pk,predecessor_operation_pk','execution_operation','execution_authority_version_pk,execution_operation_pk').ck('execution_operation_pk<>predecessor_operation_pk').lineage('execution_authority_version_pk','execution_authority_version');
const ast=T('transformation_expression_node',{expression_node_pk:'K',transformation_version_pk:'K',node_pointer:'PTR',node_kind:'CODE',operator:'ID?',literal_content_pk:'K?',reference_name:'TXT?'},'expression_node_pk').ak('transformation_version_pk,node_pointer').ak('transformation_version_pk,expression_node_pk').fk('transformation_version_pk','transformation_version').fk('literal_content_pk','source.content_object').lineage('transformation_version_pk','transformation_version');
enumCheck(ast,'node_kind',['OPERATOR','OBJECT','ARRAY','LITERAL','REFERENCE']);
ast.ck("(node_kind='OPERATOR' AND operator IS NOT NULL AND literal_content_pk IS NULL AND reference_name IS NULL) OR (node_kind IN ('OBJECT','ARRAY') AND operator IS NULL AND literal_content_pk IS NULL AND reference_name IS NULL) OR (node_kind='LITERAL' AND operator IS NULL AND literal_content_pk IS NOT NULL AND reference_name IS NULL) OR (node_kind='REFERENCE' AND operator IS NULL AND literal_content_pk IS NULL AND reference_name IS NOT NULL)");
const ach=T('transformation_expression_child',{transformation_version_pk:'K',parent_node_pk:'K',child_node_pk:'K',member_kind:'CODE',member_name:'PTR?',ordinal:'N?'},'parent_node_pk,child_node_pk',{identity:false}).ak('child_node_pk').fk('transformation_version_pk,parent_node_pk','transformation_expression_node','transformation_version_pk,expression_node_pk').fk('transformation_version_pk,child_node_pk','transformation_expression_node','transformation_version_pk,expression_node_pk').ck('parent_node_pk<>child_node_pk').ck("(member_kind='OBJECT_MEMBER' AND member_name IS NOT NULL AND ordinal IS NULL) OR (member_kind='ARRAY_MEMBER' AND member_name IS NULL AND ordinal IS NOT NULL)").ux('parent_node_pk,member_name','member_name IS NOT NULL').ux('parent_node_pk,ordinal','ordinal IS NOT NULL').lineage('transformation_version_pk','transformation_version');
T('transformation_root',{transformation_version_pk:'K',expression_node_pk:'K'},'transformation_version_pk',{identity:false}).fk('transformation_version_pk,expression_node_pk','transformation_expression_node','transformation_version_pk,expression_node_pk').lineage('transformation_version_pk','transformation_version');
T('expression_semantic_reference',{expression_node_pk:'K',semantic_object_definition_pk:'K',expected_kind:'CODE'},'expression_node_pk',{identity:false}).fk('expression_node_pk','transformation_expression_node','expression_node_pk').fk('semantic_object_definition_pk,expected_kind','semantic_object_definition','semantic_object_definition_pk,object_kind').lineage('expression_node_pk','transformation_expression_node','_owner_definition_pk');
T('operation_transformation',{execution_operation_pk:'K',transformation_version_pk:'K',role:'CODE'},'execution_operation_pk,transformation_version_pk,role',{identity:false}).fk('execution_operation_pk','execution_operation').fk('transformation_version_pk','transformation_version').lineage('execution_operation_pk','execution_operation','_owner_definition_pk');

function contextualUnique(t,key,profile,role){
  return t.ux(key,`${profile} IS NULL AND ${role} IS NULL`).ux([...list(key),profile],`${profile} IS NOT NULL AND ${role} IS NULL`).ux([...list(key),role],`${profile} IS NULL AND ${role} IS NOT NULL`).ux([...list(key),profile,role],`${profile} IS NOT NULL AND ${role} IS NOT NULL`);
}
for(const target of ['port','mechanic']){
  const n='provider_'+target+'_implementation',v=target+'_version_pk';
  contextualUnique(T(n,{[n+'_pk']:'K',provider_definition_pk:'K',[v]:'K',provider_profile_version_pk:'K?',role:'ID?'},n+'_pk').ak(['provider_definition_pk',n+'_pk',v]).fk('provider_definition_pk','provider_definition').fk(v,target+'_version').fk('provider_profile_version_pk','provider_profile_version').lineage('provider_definition_pk','provider_definition'),['provider_definition_pk',v],'provider_profile_version_pk','role');
}
T('provider_capability_implementation',{provider_definition_pk:'K',capability_version_pk:'K',role:'CODE'},'provider_definition_pk,capability_version_pk,role',{identity:false}).fk('provider_definition_pk','provider_definition').fk('capability_version_pk','capability_version').lineage('provider_definition_pk','provider_definition');
T('provider_profile_constraint',{provider_profile_version_pk:'K',ordinal:'N',constraint_kind:'CODE',constraint_term:'TXT',operand_content_pk:'K?'},'provider_profile_version_pk,ordinal',{identity:false}).fk('provider_profile_version_pk','provider_profile_version').fk('operand_content_pk','source.content_object').lineage('provider_profile_version_pk','provider_profile_version');
T('provider_slot',{provider_slot_pk:'K',blueprint_version_pk:'K',slot_id:'ID',owner_node_pk:'K'},'provider_slot_pk').ak('blueprint_version_pk,slot_id').ak('blueprint_version_pk,provider_slot_pk').ak('provider_slot_pk,blueprint_version_pk,owner_node_pk').fk('blueprint_version_pk,owner_node_pk','blueprint_node','blueprint_version_pk,blueprint_node_pk').lineage('blueprint_version_pk','blueprint_version');
for(const target of ['port','mechanic','profile']){
  const n='slot_'+target+'_requirement',v=(target==='profile'?'provider_profile':target)+'_version_pk';
  T(n,{[n+'_pk']:'K',provider_slot_pk:'K',[v]:'K',ordinal:'N',role:'ID?'},n+'_pk').ak('provider_slot_pk,ordinal').ak(['provider_slot_pk',n+'_pk',v]).ux(['provider_slot_pk',v],'role IS NULL').ux(['provider_slot_pk',v,'role'],'role IS NOT NULL').fk('provider_slot_pk','provider_slot').fk(v,(target==='profile'?'provider_profile':target)+'_version').lineage('provider_slot_pk','provider_slot','_owner_definition_pk');
}
T('slot_profile_constraint',{provider_slot_pk:'K',ordinal:'N',constraint_kind:'CODE',constraint_term:'TXT',operand_content_pk:'K?'},'provider_slot_pk,ordinal',{identity:false}).fk('provider_slot_pk','provider_slot').fk('operand_content_pk','source.content_object').lineage('provider_slot_pk','provider_slot','_owner_definition_pk');
T('binding_context',{binding_context_pk:'K',context_digest:'D',target_id:'ID?',environment_id:'ID?',provider_profile_version_pk:'K?',canonical_content_pk:'K'},'binding_context_pk').ak('context_digest').fk('provider_profile_version_pk','provider_profile_version').fk('canonical_content_pk','source.content_object').ck('target_id IS NOT NULL OR environment_id IS NOT NULL OR provider_profile_version_pk IS NOT NULL');
const scope=contextualUnique(T('provider_binding_scope',{provider_binding_scope_pk:'K',provider_slot_pk:'K',binding_context_pk:'K?',binding_role:'ID?',selection_policy:'CODE'},'provider_binding_scope_pk').ak('provider_binding_scope_pk,provider_slot_pk,selection_policy').fk('provider_slot_pk','provider_slot').fk('binding_context_pk','binding_context').lineage('provider_slot_pk','provider_slot','_owner_definition_pk'),'provider_slot_pk','binding_context_pk','binding_role');
enumCheck(scope,'selection_policy',['SINGLE','ORDERED_SET']);
T('provider_binding',{provider_binding_pk:'K',provider_binding_scope_pk:'K',provider_slot_pk:'K',selection_policy:'CODE',provider_definition_pk:'K',ordinal:'N?'},'provider_binding_pk').fk('provider_binding_scope_pk,provider_slot_pk,selection_policy','provider_binding_scope','provider_binding_scope_pk,provider_slot_pk,selection_policy').fk('provider_definition_pk','provider_definition').ak('provider_binding_pk,provider_slot_pk,provider_definition_pk').ak('provider_binding_scope_pk,provider_definition_pk').ux('provider_binding_scope_pk',"selection_policy='SINGLE'").ux('provider_binding_scope_pk,ordinal',"selection_policy='ORDERED_SET'").ck("(selection_policy='SINGLE' AND ordinal IS NULL) OR (selection_policy='ORDERED_SET' AND ordinal IS NOT NULL)").lineage('provider_slot_pk','provider_slot','_owner_definition_pk');
for(const target of ['port','mechanic']){
  const r='slot_'+target+'_requirement_pk',i='provider_'+target+'_implementation_pk',v=target+'_version_pk';
  T('binding_'+target+'_implementation',{provider_binding_pk:'K',provider_slot_pk:'K',provider_definition_pk:'K',[r]:'K',[v]:'K',[i]:'K'},['provider_binding_pk',r],{identity:false}).fk('provider_binding_pk,provider_slot_pk,provider_definition_pk','provider_binding','provider_binding_pk,provider_slot_pk,provider_definition_pk').fk(['provider_slot_pk',r,v],'slot_'+target+'_requirement',['provider_slot_pk',r,v]).fk(['provider_definition_pk',i,v],'provider_'+target+'_implementation',['provider_definition_pk',i,v]).lineage('provider_slot_pk','provider_slot','_owner_definition_pk');
}
T('provider_slot_operation',{provider_slot_pk:'K',execution_operation_pk:'K'},'provider_slot_pk,execution_operation_pk',{identity:false}).fk('provider_slot_pk','provider_slot').fk('execution_operation_pk','execution_operation').lineage('provider_slot_pk','provider_slot','_owner_definition_pk');

const bn=T('blueprint_node',{blueprint_node_pk:'K',blueprint_version_pk:'K',node_id:'ID',node_kind:'CODE',altitude:'CODE',projection_ordinal:'N',semantic_object_definition_pk:'K?',expected_semantic_kind:'CODE?',terminal_disposition:'ID?'},'blueprint_node_pk').ak('blueprint_version_pk,node_id').ak('blueprint_version_pk,blueprint_node_pk').fk('blueprint_version_pk','blueprint_version').fk('semantic_object_definition_pk,expected_semantic_kind','semantic_object_definition','semantic_object_definition_pk,object_kind').lineage('blueprint_version_pk','blueprint_version');
pairs(bn,'semantic_object_definition_pk','expected_semantic_kind');enumCheck(bn,'altitude',['CAPABILITY','OPERATION','MECHANIC','PROVIDER']);enumCheck(bn,'node_kind',['state','responsibility','outcome','junction','convergence','provider-slot','terminal']);
enumCheck(T('blueprint_node_face',{blueprint_node_pk:'K',position:'CODE',semantic_object_definition_pk:'K',expected_kind:'CODE'},'blueprint_node_pk,position',{identity:false}).fk('blueprint_node_pk','blueprint_node').fk('semantic_object_definition_pk,expected_kind','semantic_object_definition','semantic_object_definition_pk,object_kind').lineage('blueprint_node_pk','blueprint_node','_owner_definition_pk'),'position',['FIRST','ENERGIZED','RESULT']);
T('blueprint_node_scenario',{blueprint_version_pk:'K',blueprint_node_pk:'K',scenario_version_pk:'K'},'blueprint_node_pk',{identity:false}).ak('blueprint_version_pk,blueprint_node_pk,scenario_version_pk').fk('blueprint_version_pk,blueprint_node_pk','blueprint_node','blueprint_version_pk,blueprint_node_pk').fk('scenario_version_pk','scenario_version').lineage('blueprint_version_pk','blueprint_version');
const edge=T('blueprint_edge',{blueprint_edge_pk:'K',blueprint_version_pk:'K',edge_id:'ID',from_node_pk:'K',to_node_pk:'K',topology_role:'CODE',contract_relation:'CODE?',semantic_progress:'CODE?',source_scenario_version_pk:'K?',selecting_variant_pk:'K?',semantic_precedence:'CODE',projection_ordinal:'N',binding_authority_definition_pk:'K'},'blueprint_edge_pk').ak('blueprint_version_pk,edge_id').ak('blueprint_version_pk,blueprint_edge_pk').ak('blueprint_edge_pk,contract_relation').fk('blueprint_version_pk,from_node_pk','blueprint_node','blueprint_version_pk,blueprint_node_pk').fk('blueprint_version_pk,to_node_pk','blueprint_node','blueprint_version_pk,blueprint_node_pk').fk('blueprint_version_pk,from_node_pk,source_scenario_version_pk','blueprint_node_scenario','blueprint_version_pk,blueprint_node_pk,scenario_version_pk').fk('source_scenario_version_pk,selecting_variant_pk','outcome_variant','scenario_version_pk,outcome_variant_pk').fk('binding_authority_definition_pk','semantic_object_definition').lineage('blueprint_version_pk','blueprint_version');
pairs(edge,'source_scenario_version_pk','selecting_variant_pk');enumCheck(edge,'topology_role',['TRANSITION','BRANCH_ROUTE','FAN_OUT_MEMBER','CONVERGENCE_REQUIREMENT','ALTITUDE_DESCENT','BOUNDED_RETURN']);enumCheck(edge,'contract_relation',['SATISFIES','REQUIRES'],true);enumCheck(edge,'semantic_progress',['NARROWS','ESTABLISHES','TERMINATES','DESCENDS','BOUNDED_RETURN'],true);enumCheck(edge,'semantic_precedence',['REQUIRED','INDEPENDENT']);
edge.ck("topology_role<>'BRANCH_ROUTE' OR (selecting_variant_pk IS NOT NULL AND semantic_progress IS NOT NULL)").ck("topology_role NOT IN ('TRANSITION','FAN_OUT_MEMBER','CONVERGENCE_REQUIREMENT','ALTITUDE_DESCENT') OR selecting_variant_pk IS NULL").ck("topology_role NOT IN ('TRANSITION','FAN_OUT_MEMBER','ALTITUDE_DESCENT') OR semantic_progress IS NOT NULL").ck("topology_role<>'CONVERGENCE_REQUIREMENT' OR (contract_relation IS NOT NULL AND contract_relation='REQUIRES')").ck("topology_role<>'ALTITUDE_DESCENT' OR (semantic_progress IS NOT NULL AND semantic_progress='DESCENDS')").ck("topology_role<>'BOUNDED_RETURN' OR (semantic_progress IS NOT NULL AND semantic_progress='BOUNDED_RETURN')");
enumCheck(T('blueprint_edge_contract',{blueprint_edge_pk:'K',contract_relation:'CODE',product_definition_pk:'K',downstream_scenario_version_pk:'K',compatibility_authority_definition_pk:'K?'},'blueprint_edge_pk',{identity:false}).fk('blueprint_edge_pk,contract_relation','blueprint_edge','blueprint_edge_pk,contract_relation').fk('product_definition_pk','product_definition').fk('downstream_scenario_version_pk','scenario_input','scenario_version_pk').fk('compatibility_authority_definition_pk','semantic_object_definition').lineage('blueprint_edge_pk','blueprint_edge','_owner_definition_pk'),'contract_relation',['SATISFIES','REQUIRES']);
T('blueprint_convergence_requirement',{blueprint_version_pk:'K',convergence_node_pk:'K',product_definition_pk:'K'},'convergence_node_pk,product_definition_pk',{identity:false}).fk('blueprint_version_pk,convergence_node_pk','blueprint_node','blueprint_version_pk,blueprint_node_pk').fk('product_definition_pk','product_definition').lineage('blueprint_version_pk','blueprint_version');
T('blueprint_fan_out_set',{blueprint_fan_out_set_pk:'K',blueprint_version_pk:'K',fan_out_set_id:'ID'},'blueprint_fan_out_set_pk').ak('blueprint_version_pk,fan_out_set_id').ak('blueprint_version_pk,blueprint_fan_out_set_pk').fk('blueprint_version_pk','blueprint_version').lineage('blueprint_version_pk','blueprint_version');
T('blueprint_fan_out_member',{blueprint_version_pk:'K',blueprint_fan_out_set_pk:'K',blueprint_edge_pk:'K'},'blueprint_fan_out_set_pk,blueprint_edge_pk',{identity:false}).ak('blueprint_edge_pk').fk('blueprint_version_pk,blueprint_fan_out_set_pk','blueprint_fan_out_set','blueprint_version_pk,blueprint_fan_out_set_pk').fk('blueprint_version_pk,blueprint_edge_pk','blueprint_edge','blueprint_version_pk,blueprint_edge_pk').lineage('blueprint_version_pk','blueprint_version');
enumCheck(T('blueprint_bounded_return',{blueprint_edge_pk:'K',return_kind:'CODE',declared_bound_content_pk:'K',authority_definition_pk:'K'},'blueprint_edge_pk',{identity:false}).fk('blueprint_edge_pk','blueprint_edge').fk('declared_bound_content_pk','source.content_object').fk('authority_definition_pk','semantic_object_definition').lineage('blueprint_edge_pk','blueprint_edge','_owner_definition_pk'),'return_kind',['REPAIR','RESUMPTION','ITERATION']);

address(T('fixture',{fixture_pk:'K',owner_definition_pk:'K',fixture_id:'ID',fixture_profile:'ID'},'fixture_pk').ak('owner_definition_pk,fixture_id').fk('owner_definition_pk','semantic_object_definition'),'FIXTURE','fixture_id');
T('fixture_case',{fixture_case_pk:'K',fixture_pk:'K',case_id:'ID?',ordinal:'N',input_content_pk:'K',expected_disposition:'ID?',terminal_scenario_version_pk:'K?'},'fixture_case_pk').ak('fixture_pk,ordinal').ak('fixture_pk,fixture_case_pk').ux('fixture_pk,case_id','case_id IS NOT NULL').fk('fixture_pk','fixture').fk('input_content_pk','source.content_object').fk('terminal_scenario_version_pk','scenario_version').lineage('fixture_pk','fixture');
T('fixture_assertion',{fixture_assertion_pk:'K',fixture_case_pk:'K',ordinal:'N',condition_id:'ID?',path:'TXT',operator:'ID',expected_value_content_pk:'K'},'fixture_assertion_pk').ak('fixture_case_pk,ordinal').fk('fixture_case_pk','fixture_case').fk('expected_value_content_pk','source.content_object').lineage('fixture_case_pk','fixture_case','_owner_definition_pk');
T('fixture_scenario_step',{fixture_case_pk:'K',ordinal:'N',scenario_version_pk:'K'},'fixture_case_pk,ordinal',{identity:false}).fk('fixture_case_pk','fixture_case').fk('scenario_version_pk','scenario_version').lineage('fixture_case_pk','fixture_case','_owner_definition_pk');
T('fixture_port_outcome',{fixture_case_pk:'K',port_version_pk:'K',ordinal:'N',content_object_pk:'K'},'fixture_case_pk,port_version_pk,ordinal',{identity:false}).fk('fixture_case_pk','fixture_case').fk('port_version_pk','port_version').fk('content_object_pk','source.content_object').lineage('fixture_case_pk','fixture_case','_owner_definition_pk');
address(T('observable_condition',{observable_condition_pk:'K',owner_definition_pk:'K',condition_id:'ID',statement:'TXT?'},'observable_condition_pk').ak('owner_definition_pk,condition_id').fk('owner_definition_pk','semantic_object_definition'),'OBSERVABLE_CONDITION','condition_id');
T('fixture_assertion_condition',{fixture_assertion_pk:'K',observable_condition_pk:'K'},'fixture_assertion_pk,observable_condition_pk',{identity:false}).fk('fixture_assertion_pk','fixture_assertion').fk('observable_condition_pk','observable_condition').lineage('fixture_assertion_pk','fixture_assertion','_owner_definition_pk');
address(T('proof_obligation',{proof_obligation_pk:'K',owner_definition_pk:'K',proof_obligation_id:'ID',obligation_kind:'CODE',statement:'TXT?'},'proof_obligation_pk').ak('owner_definition_pk,proof_obligation_id').fk('owner_definition_pk','semantic_object_definition'),'PROOF_OBLIGATION','proof_obligation_id');
T('proof_obligation_subject',{proof_obligation_pk:'K',subject_definition_pk:'K',role:'CODE'},'proof_obligation_pk,subject_definition_pk,role',{identity:false}).fk('proof_obligation_pk','proof_obligation').fk('subject_definition_pk','semantic_object_definition').lineage('proof_obligation_pk','proof_obligation');
T('proof_obligation_fixture',{proof_obligation_pk:'K',fixture_case_pk:'K',role:'CODE'},'proof_obligation_pk,fixture_case_pk,role',{identity:false}).fk('proof_obligation_pk','proof_obligation').fk('fixture_case_pk','fixture_case').lineage('proof_obligation_pk','proof_obligation');
for(const [n,parent] of [['c4_context',null],['c4_container','c4_context'],['c4_component','c4_container']]){
  const t=address(T(n,{[n+'_pk']:'K',blueprint_version_pk:'K',element_id:'ID',realization_authority_definition_pk:'K'},n+'_pk').ak('blueprint_version_pk,element_id').ak(['blueprint_version_pk',n+'_pk']).fk('blueprint_version_pk','blueprint_version').fk('realization_authority_definition_pk','semantic_object_definition'),n.toUpperCase(),'element_id');
  if(parent)t.col(parent+'_pk','K?').fk(['blueprint_version_pk',parent+'_pk'],parent,['blueprint_version_pk',parent+'_pk']);
}
T('c4_code_mapping',{c4_code_mapping_pk:'K',blueprint_version_pk:'K',ordinal:'N',element_id:'ID?',c4_component_pk:'K?',realization_authority_definition_pk:'K',code_locator:'TXT?'},'c4_code_mapping_pk').ak('blueprint_version_pk,ordinal').ak('blueprint_version_pk,c4_code_mapping_pk').ux('blueprint_version_pk,element_id','element_id IS NOT NULL').fk('blueprint_version_pk','blueprint_version').fk('blueprint_version_pk,c4_component_pk','c4_component','blueprint_version_pk,c4_component_pk').fk('realization_authority_definition_pk','semantic_object_definition').lineage('blueprint_version_pk','blueprint_version');
for(const n of ['c4_context','c4_container','c4_component','c4_code_mapping'])T(n+'_node',{blueprint_version_pk:'K',[n+'_pk']:'K',blueprint_node_pk:'K'},[n+'_pk','blueprint_node_pk'],{identity:false}).fk(['blueprint_version_pk',n+'_pk'],n,['blueprint_version_pk',n+'_pk']).fk('blueprint_version_pk,blueprint_node_pk','blueprint_node','blueprint_version_pk,blueprint_node_pk').lineage('blueprint_version_pk','blueprint_version');
T('observed_semantic_graph_transition',{source_observation_pk:'K',transition_id:'ID?',from_scenario_ref:'TXT?',from_outcome_ref:'TXT?',to_scenario_ref:'TXT?',to_input_ref:'TXT?',declared_topology:'ID?',declared_progress:'ID?',selected_variant_ref:'TXT?'},'source_observation_pk',{identity:false}).fk('source_observation_pk','source.relationship_observation','source_observation_pk');
T('observed_execution_scenario_invocation',{source_observation_pk:'K',execution_authority_ref:'TXT?',operation_ordinal:'N',target_scenario_ref:'TXT?'},'source_observation_pk',{identity:false}).fk('source_observation_pk','source.relationship_observation','source_observation_pk');
T('observed_transition_resolution',{estate_model_pk:'K',source_observation_pk:'K',source_scenario_version_pk:'K',target_scenario_version_pk:'K',selecting_variant_pk:'K?'},'estate_model_pk,source_observation_pk',{identity:false}).fk('estate_model_pk','source.estate_model').fk('source_observation_pk','observed_semantic_graph_transition','source_observation_pk').fk('source_scenario_version_pk','scenario_version').fk('target_scenario_version_pk','scenario_version').fk('source_scenario_version_pk,selecting_variant_pk','outcome_variant','scenario_version_pk,outcome_variant_pk');
T('observed_invocation_resolution',{estate_model_pk:'K',source_observation_pk:'K',execution_operation_pk:'K'},'estate_model_pk,source_observation_pk',{identity:false}).fk('estate_model_pk','source.estate_model').fk('source_observation_pk','observed_execution_scenario_invocation','source_observation_pk').fk('execution_operation_pk','operation_scenario_invocation','execution_operation_pk');
for(const role of ['transition','invocation'])T('blueprint_observed_'+role+'_mapping',{estate_model_pk:'K',blueprint_edge_pk:'K',source_observation_pk:'K',mapping_authority_definition_pk:'K'},'estate_model_pk,blueprint_edge_pk,source_observation_pk,mapping_authority_definition_pk',{identity:false}).fk('estate_model_pk','source.estate_model').fk('blueprint_edge_pk','blueprint_edge').fk('source_observation_pk',role==='transition'?'observed_semantic_graph_transition':'observed_execution_scenario_invocation','source_observation_pk').fk('mapping_authority_definition_pk','semantic_object_definition');

T('analysis.integrity_rule',{integrity_rule_pk:'K',rule_id:'ID',rule_digest:'D',layer:'tinyint',rule_content_pk:'K'},'integrity_rule_pk').ak('rule_id,rule_digest').fk('rule_content_pk','source.content_object').ck('layer IN (1,2)');
enumCheck(T('analysis.assessment',{assessment_pk:'K',estate_model_pk:'K',integrity_rule_pk:'K',assessment_kind:'CODE',scope_digest:'D',input_set_digest:'D',evaluation_state:'CODE',evaluated_at:'T?'},'assessment_pk').ak('estate_model_pk,integrity_rule_pk,assessment_kind,scope_digest,input_set_digest').ak('assessment_pk,assessment_kind').fk('estate_model_pk','source.estate_model').fk('integrity_rule_pk','analysis.integrity_rule'),'evaluation_state',['EVALUATED','NOT_EVALUATED','OUTSIDE_CURRENT_MODEL']);
T('analysis.assessment_source_input',{assessment_pk:'K',source_observation_pk:'K',role:'CODE'},'assessment_pk,source_observation_pk,role',{identity:false}).fk('assessment_pk','analysis.assessment').fk('source_observation_pk','source.source_observation');
T('analysis.assessment_definition_input',{assessment_pk:'K',semantic_object_definition_pk:'K',role:'CODE'},'assessment_pk,semantic_object_definition_pk,role',{identity:false}).fk('assessment_pk','analysis.assessment').fk('semantic_object_definition_pk','semantic_object_definition');
enumCheck(T('analysis.integrity_finding',{integrity_finding_pk:'K',assessment_pk:'K',finding_digest:'D',finding_code:'CODE',severity:'CODE',source_observation_pk:'K?',subject_definition_pk:'K?',expected_content_pk:'K?',observed_content_pk:'K?',message:'TXT'},'integrity_finding_pk').ak('assessment_pk,finding_digest').fk('assessment_pk','analysis.assessment').fk('source_observation_pk','source.source_observation').fk('subject_definition_pk','semantic_object_definition').fk('expected_content_pk','source.content_object').fk('observed_content_pk','source.content_object'),'severity',['INFO','WARNING','ERROR']);
enumCheck(T('analysis.unresolved_reference',{estate_model_pk:'K',source_observation_pk:'K',reference_role:'CODE',resolution_state:'CODE',finding_pk:'K?'},'estate_model_pk,source_observation_pk,reference_role',{identity:false}).fk('estate_model_pk','source.estate_model').fk('source_observation_pk','source.relationship_observation','source_observation_pk').fk('finding_pk','analysis.integrity_finding'),'resolution_state',['MISSING_ID','MISSING_TARGET','AMBIGUOUS_TARGET','WRONG_KIND','PROFILE_UNSUPPORTED','NAMESPACE_UNMAPPED','DEFINITION_UNRESOLVED']);
export function assessment(name,kind,cols){return fixed(T('analysis.'+name,{assessment_pk:'K',...cols},'assessment_pk',{identity:false}),'assessment_kind',kind).fk('assessment_pk,assessment_kind','analysis.assessment','assessment_pk,assessment_kind');}
enumCheck(assessment('compatibility_assessment','COMPATIBILITY',{producer_contract_version_pk:'K',consumer_contract_version_pk:'K',authority_definition_pk:'K?',result_code:'CODE?'}).fk('producer_contract_version_pk','contract_version').fk('consumer_contract_version_pk','contract_version').fk('authority_definition_pk','semantic_object_definition'),'result_code',['COMPATIBLE','INCOMPATIBLE'],true);
enumCheck(assessment('coverage_assessment','COVERAGE',{source_profile:'ID',count_unit:'CODE',total_count:'bigint',normalized_count:'bigint',unresolved_count:'bigint',unsupported_count:'bigint',outside_count:'bigint'}).ck('total_count>=0 AND normalized_count>=0 AND unresolved_count>=0 AND unsupported_count>=0 AND outside_count>=0 AND total_count=normalized_count+unresolved_count+unsupported_count+outside_count'),'count_unit',['APPEARANCE','OBSERVATION']);
enumCheck(assessment('circuit_assessment','CIRCUIT',{blueprint_version_pk:'K',blueprint_node_pk:'K?',result_code:'CODE?'}).fk('blueprint_version_pk','blueprint_version').fk('blueprint_version_pk,blueprint_node_pk','blueprint_node','blueprint_version_pk,blueprint_node_pk'),'result_code',['CHECKED_CLEAR','FINDINGS','INCOMPLETE','NOT_APPLICABLE'],true);
assessment('provider_qualification_assessment','PROVIDER_QUALIFICATION',{provider_definition_pk:'K',provider_profile_version_pk:'K?',provider_slot_pk:'K?',authority_definition_pk:'K',rule_definition_pk:'K',result_code:'ID',effective_until:'T?',source_observation_pk:'K'}).fk('provider_definition_pk','provider_definition').fk('provider_profile_version_pk','provider_profile_version').fk('provider_slot_pk','provider_slot').fk('authority_definition_pk','semantic_object_definition').fk('rule_definition_pk','semantic_object_definition').fk('source_observation_pk','source.source_observation');

for(const [name,cols] of Object.entries({
  'model.estate_definition':['semantic_object_definition_pk','estate_model_pk'],
  'model.capability_scenario':['scenario_version_pk','capability_version_pk'],
  'model.outcome_product':['product_definition_pk','scenario_version_pk'],
  'model.outcome_variant_product':['product_definition_pk','outcome_variant_pk'],
  'model.provider_binding':['provider_definition_pk','provider_slot_pk'],
  'model.provider_slot_operation':['execution_operation_pk','provider_slot_pk'],
  'model.blueprint_edge':['blueprint_version_pk','from_node_pk'],
  'model.blueprint_node':['blueprint_version_pk','altitude','node_kind'],
  'analysis.assessment':['estate_model_pk','assessment_kind','integrity_rule_pk'],
  'analysis.integrity_finding':['assessment_pk','severity','finding_code']
}))tables.get(name).ix(cols);
tables.get('model.blueprint_edge').ix('blueprint_version_pk,to_node_pk');

export function validateCatalog(){
  for(const t of tables.values()){
    for(const cols of [t.pk,...t.aks,...t.indexes,...t.filtered.map(f=>f.cols)])for(const c of cols)if(!t.columns[c])throw new Error('UNKNOWN_KEY_COLUMN:'+t.name+':'+c);
    for(const f of t.fks){
      const target=tables.get(f.target);if(!target)throw new Error('UNKNOWN_FK_TABLE:'+f.target);
      for(const c of f.cols)if(!t.columns[c])throw new Error('UNKNOWN_FK_COLUMN:'+t.name+':'+c);
      if(f.cols.length!==f.targetCols.length)throw new Error('FK_ARITY:'+t.name);
      if(![target.pk,...target.aks].some(a=>a.join()===f.targetCols.join()))throw new Error('FK_WITHOUT_CANDIDATE_KEY:'+t.name+':'+f.target+':'+f.targetCols);
      for(let i=0;i<f.cols.length;i++)if(t.columns[f.cols[i]].type!==target.columns[f.targetCols[i]]?.type)throw new Error('FK_TYPE_MISMATCH:'+t.name+':'+f.cols[i]);
    }
    if(t.owner&&!t.owner.self){const p=tables.get(t.owner.parent);if(!p?.columns[t.owner.target])throw new Error('INVALID_OWNER:'+t.name);}
  }
  return {tables:tables.size,foreignKeys:[...tables.values()].reduce((a,t)=>a+t.fks.length,0),alternateKeys:[...tables.values()].reduce((a,t)=>a+t.aks.length,0)};
}
validateCatalog();
