import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Dataset,canonical,parseJson,bytesDigest,validId,pointer} from './data.mjs';
import {digest} from './catalog.mjs';
import {parseFeature,featureScenarios,tagsToValues} from '../derive/feature.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const cleanAst=v=>Array.isArray(v)?v.map(cleanAst):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).filter(([k,x])=>x!==undefined&&!['location','id','comments'].includes(k)).map(([k,x])=>[k,cleanAst(x)])):v;
const one=(tags,k)=>tags[k]?.length===1&&validId(tags[k][0])?tags[k][0]:null;
const semanticFile=a=>/\.feature$|authority\.json$|contract-catalog\.json$|provider-catalog\.json$|\.profile\.json$|semantic-carrier.*\.json$|execution-plan.*\.json$/.test(a.sourcePath);

export async function normalize(){
 const ds=new Dataset(),mapping=parseJson(await fs.readFile(path.join(root,'config/normalization-v1.json'))),snapshotFile=path.join(root,'data/snapshots',mapping.selectedSnapshot.slice(7)+'.json');
 const snapshot=parseJson(await fs.readFile(snapshotFile));if(snapshot.snapshotId!==mapping.selectedSnapshot)throw new Error('SNAPSHOT_SELECTION_MISMATCH');
 const sourceCopy={...snapshot};delete sourceCopy.snapshotId;
 // The snapshot contract hashes compact stable JSON; the storage newline is not hashed.
 if('sha256:'+digest(canonical(sourceCopy))!==snapshot.snapshotId)throw new Error('SNAPSHOT_DIGEST_MISMATCH');
 ds.snapshot=ds.add('source.estate_snapshot',{snapshot_digest:Buffer.from(snapshot.snapshotId.slice(7),'hex'),estate_manifest_digest:Buffer.from(snapshot.estateManifestDigest.slice(7),'hex'),source_head:snapshot.sourceHead,captured_at:null});
 const implementation={};for(const name of ['src/migration/normalize.mjs','src/migration/data.mjs','src/derive/feature.mjs','package-lock.json'])implementation[name]=digest(await fs.readFile(path.join(root,name)));
 const rc=ds.json({...mapping,implementation});ds.rule=ds.add('source.mapping_rule',{rule_id:mapping.ruleId,rule_digest:rc.content_digest,source_profile:mapping.profile,rule_content_object_pk:rc.content_object_pk,canonicalization_profile:mapping.canonicalization});
 ds.model=ds.add('source.estate_model',{estate_snapshot_pk:ds.snapshot.estate_snapshot_pk,mapping_manifest_digest:bytesDigest(canonical([{id:mapping.ruleId,digest:rc.content_digest.toString('hex')}])),publication_state:'BUILDING'});
 ds.add('source.estate_model_rule',{estate_model_pk:ds.model.estate_model_pk,mapping_rule_pk:ds.rule.mapping_rule_pk});
 const artifacts=[],blobCache=new Map();
 for(const a of snapshot.artifacts){let c=blobCache.get(a.contentDigest);if(!c){const h=a.contentDigest.slice(7),b=await fs.readFile(path.join(root,'data/objects',h.slice(0,2),h));if(digest(b)!==h)throw new Error('SOURCE_CONTENT_MISMATCH');c=ds.content(b);blobCache.set(a.contentDigest,c);}if(c.byte_length!==a.byteLength)throw new Error('SOURCE_LENGTH_MISMATCH');
   const appearance=ds.add('source.source_appearance',{estate_snapshot_pk:ds.snapshot.estate_snapshot_pk,content_object_pk:c.content_object_pk,appearance_digest:Buffer.from(a.artifactId.slice(7),'hex'),source_path:a.sourcePath,source_class:a.sourceClass,container_locator:a.containerPath,capsule_digest:a.capsuleDigest?Buffer.from(a.capsuleDigest.slice(7),'hex'):null,referenced_authority_digest:a.authorityDigest?Buffer.from(a.authorityDigest.slice(7),'hex'):null,entry_id:a.entryId});
   const item={...a,appearance,bytes:c.content_bytes,classification:semanticFile(a)?'UNSUPPORTED':'OUTSIDE_SCOPE',family:semanticFile(a)?'UNMAPPED_SEMANTIC_SOURCE':'OTHER_SOURCE'};
   if(a.sourcePath.endsWith('.json')&&a.byteLength<4000000){try{item.json=parseJson(item.bytes);}catch(e){if(semanticFile(a))item.parseError=e.message;}}
   artifacts.push(item);
 }
 const obs=(a,loc,value,kind='DOCUMENT',id=null)=>ds.observation(a.appearance,loc,'DECLARATION',value,{kind,id});
 const issue=(a,code,message,loc='',kind='DOCUMENT',value=null)=>{const o=obs(a,loc,value,kind);ds.issues.push({code,message,observation:o});return o;};
 const mark=(a,family)=>{a.classification='SUPPORTED';a.family=family;};
 const namespace=(kind,id)=>{const n=ds.namespace(kind,id);ds.add('source.namespace_mapping',{mapping_rule_pk:ds.rule.mapping_rule_pk,object_kind:kind,source_scope:id,namespace_pk:n.namespace_pk},{dedup:true});return n;};
 // A shared library declares its authorities once for the estate under an explicitly bound namespace. Bind them before capsule scenarios so a scenario event can resolve a shared authority it declares. Operations are members of the shared library's own mapping.
 const sharedExecs=new Map();
 for(const [label,scope]of [['agentic',mapping.namespaceBindings.sharedAgentic],['feature-authoring',mapping.namespaceBindings.sharedFeatureAuthoring]]){
  const a=artifacts.find(x=>(x.entryId??x.sourcePath)===`semantic-authority/${label}-execution-authorities.authority.json`&&x.json?.authorityType==='execution-authorities.v1');
  if(!a||!scope)continue;
  for(const [i,e]of (a.json.executionAuthorities??[]).entries()){if(!validId(e.id)||!Array.isArray(e.operations))continue;
   const o=obs(a,`/executionAuthorities/${i}`,e,'EXECUTION_AUTHORITY',e.id),d=ds.definition(ds.identity('EXECUTION_AUTHORITY',e.id,namespace('EXECUTION_AUTHORITY',scope)),e,{authority_profile:'execution-authorities.v1'},[o]);
   if(!sharedExecs.has(e.id))sharedExecs.set(e.id,[]);sharedExecs.get(e.id).push({d,scenario:e.owningScenarioId});}
 }
 const groups=new Map();for(const a of artifacts.filter(a=>a.sourceClass==='MANAGED_CAPSULE')){if(!groups.has(a.capsuleDigest))groups.set(a.capsuleDigest,[]);groups.get(a.capsuleDigest).push(a);}
 for(const bundle of groups.values()){
  const exact=id=>{const xs=bundle.filter(a=>a.entryId===id);if(xs.length>1&&new Set(xs.map(a=>a.contentDigest)).size>1)throw new Error('CONFLICTING_CAPSULE_ROLE:'+id);return xs[0];};
  // A relative locator is declared against its document's repository path. A capsule entry name is a packaging alias, so a locator that leaves the entry root still resolves through the captured source path within the same capsule.
  const exactSource=p=>{const xs=bundle.filter(a=>a.sourcePath===p);if(xs.length>1&&new Set(xs.map(a=>a.contentDigest)).size>1)throw new Error('CONFLICTING_CAPSULE_SOURCE:'+p);return xs[0];};
  const relative=(from,locator)=>path.posix.normalize(path.posix.join(path.posix.dirname(from),locator));
  const ca=exact('capability.authority.json');if(!ca?.json||!validId(ca.json.capabilityId)||ca.json.capabilityId!==ca.capabilityId){if(ca)issue(ca,'INVALID_CAPABILITY_DECLARATION','Capability declaration does not match the verified capsule owner.');continue;}
  const cj=ca.json,capId=cj.capabilityId,capIdentity=ds.identity('CAPABILITY',capId,namespace('CAPABILITY',mapping.namespaceBindings.CAPABILITY));
  const features=bundle.filter(a=>a.entryId?.startsWith('features/')&&a.sourcePath.endsWith('.feature'));const uniqueFeatures=[...new Map(features.map(a=>[a.contentDigest,a])).values()];
  const parsed=[];for(const a of uniqueFeatures)try{const f=parseFeature(a.bytes.toString('utf8')).feature;if(one(tagsToValues(f.tags),'capability')!==capId)throw new Error('FEATURE_CAPABILITY_MISMATCH');parsed.push({a,f});}catch(e){issue(a,'FEATURE_PROFILE_UNSUPPORTED',e.message);}
  const contributions=[];for(const a of bundle){if(a.json&&/authority\.json$/.test(a.entryId??'')&&!/blueprint|projection/.test(a.entryId))contributions.push({role:a.entryId,fragment:digest(canonical(a.json))});}
  for(const {f} of parsed)contributions.push({role:'feature',fragment:digest(canonical(cleanAst(f)))});
  const manifest=[...new Map(contributions.map(c=>[canonical(c),c])).values()].sort((a,b)=>canonical(a)<canonical(b)?-1:1),manifestDigest=digest(canonical(manifest));
  const scenarioMembers=Object.fromEntries(parsed.flatMap(({f})=>featureScenarios(f).map(({scenario:s,inherited})=>[one(tagsToValues([...inherited,...s.tags]),'scenario'),cleanAst(s)])).filter(([id])=>id));
  const co=obs(ca,'',cj,'CAPABILITY',capId);const cap=ds.definition(capIdentity,{authority:cj,contributions:manifest,scenario_members:scenarioMembers},{name:cj.name??capId,actor:cj.userStory?.actor??null,intent:cj.userStory?.intent??null,outcome:cj.userStory?.outcome??null,experience_id:cj.experience?.experienceId??null,experience_actor:cj.experience?.actor??null,experience_promise:cj.experience?.promise??null},[co]);mark(ca,'CAPABILITY');
  ds.add('estate_capability',{estate_model_pk:ds.model.estate_model_pk,capability_pk:cap.capability_pk,capability_version_pk:cap.capability_version_pk,semantic_object_definition_pk:cap.semantic_object_definition_pk});
  const scope='sidefx:capability:'+capId,contracts=new Map(),ports=new Map(),scenarios=new Map(),transforms=new Map(),execs=new Map();
  const catalog=exact('contracts/contract-catalog.json');
  if(catalog?.json){let complete=true;for(const [id,locator]of Object.entries(catalog.json)){if(!validId(id)||typeof locator!=='string'){complete=false;continue;}const a=exact(relative(catalog.entryId,locator))??exactSource(relative(catalog.sourcePath,locator));if(!a?.json){issue(catalog,'CONTRACT_SCHEMA_UNRESOLVED','The catalog schema does not resolve to one captured JSON schema.', '/'+pointer(id),'CONTRACT',locator);complete=false;continue;}
    const schema=ds.add('schema_object',{content_digest:bytesDigest(a.bytes),dialect:a.json.$schema??null,content_object_pk:ds.content(a.bytes).content_object_pk},{dedup:true});
    const identity=ds.identity('CONTRACT',id,namespace('CONTRACT',mapping.namespaceBindings.CONTRACT));const o=obs(catalog,'/'+pointer(id),locator,'CONTRACT',id),so=obs(a,'',a.json,'SCHEMA');
    const def=ds.definition(identity,{schema_digest:bytesDigest(a.bytes).toString('hex')},{name:a.json.title??null,contract_kind:null,schema_object_pk:schema.schema_object_pk,schema_reference_state:'RESOLVED'},[o,so]);contracts.set(id,def);mark(a,'SCHEMA');
   }if(complete)mark(catalog,'CONTRACT_CATALOG');}
  const interfaces=exact('interfaces.authority.json');if(interfaces?.json?.interfaceAuthorityType==='consumer-interface-authority.v1'){
   for(const [i,p]of (interfaces.json.portBindings??[]).entries()){if(!validId(p.portId)){issue(interfaces,'PORT_ID_REQUIRED','Port declaration has no valid portId.',`/portBindings/${i}`);continue;}const o=obs(interfaces,`/portBindings/${i}`,p,'PORT',p.portId);const ident=ds.identity('PORT',p.portId,namespace('PORT',scope));const def=ds.definition(ident,p,{name:null,port_profile:'consumer-interface-authority.v1'},[o]);if(ports.has(p.portId))throw new Error('CONFLICTING_PORT_DECLARATION:'+capId+':'+p.portId);ports.set(p.portId,def);}
   // Interface declarations include additional references; do not call the entire appearance normalized.
   interfaces.family='PARTIAL_INTERFACE_AUTHORITY';
  }
  const ta=exact('semantic-transformation.authority.json');if(Array.isArray(ta?.json?.transformations)){
    let all=true;for(const [i,t]of ta.json.transformations.entries()){if(!validId(t.id)||!Object.hasOwn(t,'expression')){all=false;continue;}const o=obs(ta,`/transformations/${i}`,t,'TRANSFORMATION',t.id),ident=ds.identity('TRANSFORMATION',t.id,namespace('TRANSFORMATION',scope));const d=ds.definition(ident,t,{expression_profile:'json-expression-tree.v1'},[o]);transforms.set(t.id,d);
      const visit=(v,ptr)=>{const kind=Array.isArray(v)?'ARRAY':v&&typeof v==='object'?'OBJECT':'LITERAL';const n=ds.member('transformation_expression_node',{transformation_version_pk:d.transformation_version_pk,node_pointer:ptr,node_kind:kind,operator:null,literal_content_pk:kind==='LITERAL'?ds.json(v).content_object_pk:null,reference_name:null},d,ptr,[o]);if(kind==='OBJECT'||kind==='ARRAY')for(const [k,x]of Object.entries(v)){const child=visit(x,ptr+'/'+pointer(k));ds.member('transformation_expression_child',{transformation_version_pk:d.transformation_version_pk,parent_node_pk:n.expression_node_pk,child_node_pk:child.expression_node_pk,member_kind:kind==='ARRAY'?'ARRAY_MEMBER':'OBJECT_MEMBER',member_name:kind==='OBJECT'?k:null,ordinal:kind==='ARRAY'?Number(k):null},d,ptr+'/'+pointer(k),[o]);}return n;};const r=visit(t.expression,'/semantics/expression');ds.member('transformation_root',{transformation_version_pk:d.transformation_version_pk,expression_node_pk:r.expression_node_pk},d,'/semantics/expression',[o]);
    }if(all)mark(ta,'TRANSFORMATION');
  }
  // A declared state projection binds its projectionId to an exact transformation in this capsule's transformation authority. Any other projection form stays an observation.
  const projections=new Map();
  for(const [i,p]of (interfaces?.json?.projectionBindings??[]).entries()){if(!validId(p.projectionId)||p.configuration?.transformationAuthorityRef!=='semantic-transformation.authority.json')continue;const t=transforms.get(p.configuration?.transformationId);if(t)projections.set(p.projectionId,{d:t,ptr:`/projectionBindings/${i}`});}
  for(const {a,f}of parsed){let complete=true;for(const {scenario:s,inherited}of featureScenarios(f)){const tags=tagsToValues([...inherited,...s.tags]),id=one(tags,'scenario');if(!id||scenarios.has(id)){issue(a,'SCENARIO_ID_AMBIGUOUS','Scenario must have one unique explicit ID in this capability.',`/line/${s.location.line}`);complete=false;continue;}const o=obs(a,`/line/${s.location.line}`,cleanAst(s),'SCENARIO',id);const ident=ds.identity('SCENARIO',id,ds.ownedNamespace('SCENARIO',capIdentity),{capability_pk:cap.capability_pk});const d=ds.definition(ident,{scenario:cleanAst(s),tags,authority_manifest_digest:manifestDigest},{name:s.name,source_profile:'managed-feature-tags.v1'},[o]);scenarios.set(id,{d,s,tags,o,a});ds.member('capability_scenario',{capability_pk:cap.capability_pk,capability_version_pk:cap.capability_version_pk,scenario_pk:d.scenario_pk,scenario_version_pk:d.scenario_version_pk},cap,'/semantics/scenario_members/'+pointer(id),[co,o]);}
   if(complete)mark(a,'SCENARIO_FEATURE');
  }
  const rootScenario=scenarios.get(cj.rootScenarioId);if(rootScenario)ds.member('capability_root_scenario',{capability_version_pk:cap.capability_version_pk,scenario_pk:rootScenario.d.scenario_pk},cap,'/semantics/authority/rootScenarioId',[co]);else issue(ca,'ROOT_SCENARIO_UNRESOLVED','Declared root scenario has no uniquely normalized feature declaration.','/rootScenarioId','SCENARIO_REFERENCE',cj.rootScenarioId??null);
  const ea=exact('execution-authorities.authority.json');if(ea?.json?.authorityType==='execution-authorities.v1'){let all=true;for(const [i,e]of ea.json.executionAuthorities.entries()){
    const supported=validId(e.id)&&Array.isArray(e.operations)&&e.operations.every(op=>op.kind==='invoke-port'?ports.has(op.portId):op.kind==='invoke-scenario'?scenarios.has(op.scenarioId):op.kind==='project-state'?projections.has(op.projectionId):false);
    if(!supported){all=false;issue(ea,'EXECUTION_TARGET_UNRESOLVED','Execution authority requires a target or operation profile not resolved by this mapping.',`/executionAuthorities/${i}`,'EXECUTION_AUTHORITY',e);continue;}
    const o=obs(ea,`/executionAuthorities/${i}`,e,'EXECUTION_AUTHORITY',e.id),ident=ds.identity('EXECUTION_AUTHORITY',e.id,namespace('EXECUTION_AUTHORITY',scope));const d=ds.definition(ident,{authority:e,authority_manifest_digest:manifestDigest},{authority_profile:'execution-authorities.v1'},[o]);if(!execs.has(e.id))execs.set(e.id,[]);execs.get(e.id).push({d,scenario:e.owningScenarioId});
    for(const [j,op]of e.operations.entries()){const ptr=`/semantics/authority/operations/${j}`,r=ds.member('execution_operation',{execution_authority_version_pk:d.execution_authority_version_pk,operation_id:op.id??null,ordinal:j,operation_kind:op.kind},d,ptr,[o]);if(op.kind==='invoke-port')ds.member('operation_port_invocation',{execution_operation_pk:r.execution_operation_pk,operation_kind:op.kind,port_version_pk:ports.get(op.portId).port_version_pk},d,ptr,[o]);else if(op.kind==='project-state'){const pj=projections.get(op.projectionId);ds.member('operation_state_projection',{execution_operation_pk:r.execution_operation_pk,operation_kind:op.kind,transformation_version_pk:pj.d.transformation_version_pk},d,ptr,[o,obs(interfaces,pj.ptr,op.projectionId,'STATE_PROJECTION',op.projectionId)]);}else{ds.member('operation_scenario_invocation',{execution_operation_pk:r.execution_operation_pk,operation_kind:op.kind,target_scenario_version_pk:scenarios.get(op.scenarioId).d.scenario_version_pk},d,ptr,[o]);const ro=ds.observation(ea.appearance,`/executionAuthorities/${i}/operations/${j}`,'RELATIONSHIP',op,{role:'EXECUTION_SCENARIO_INVOCATION',source:e.id,target:op.scenarioId});ds.add('observed_execution_scenario_invocation',{source_observation_pk:ro.source_observation_pk,execution_authority_ref:e.id,operation_ordinal:j,target_scenario_ref:op.scenarioId});ds.add('observed_invocation_resolution',{estate_model_pk:ds.model.estate_model_pk,source_observation_pk:ro.source_observation_pk,execution_operation_pk:r.execution_operation_pk});}}
   }if(all)mark(ea,'EXECUTION_AUTHORITY');}
  for(const {d,s,tags,o,a}of scenarios.values()){
    for(const [role,kind]of [['input','SCENARIO_INPUT'],['event','SCENARIO_EVENT'],['outcome','SCENARIO_OUTCOME']]){const id=one(tags,role);if(!id){issue(a,'SCENARIO_FACE_UNRESOLVED','Scenario has no single explicit '+role+' ID.',`/line/${s.location.line}/tags/${role}`);continue;}const ident=ds.identity(kind,id,ds.ownedNamespace(kind,d));const stepType={input:'Context',event:'Action',outcome:'Outcome'}[role];const texts=s.steps.filter(x=>x.keywordType===stepType).map(x=>x.text).join('\n');let fields={[role+'_id']:id,name:null};const ref=role==='input'?one(tags,'input-contract'):role==='event'?one(tags,'event-authority'):null;const candidates=(execs.get(ref)??sharedExecs.get(ref)??[]).filter(x=>!x.scenario||x.scenario===d.scenario_id);const target=role==='input'?contracts.get(ref):candidates.length===1?candidates[0].d:null;
      if(role==='input')fields={...fields,input_contract_version_pk:target?.contract_version_pk??null,contract_reference_state:target?'RESOLVED':ref?'UNRESOLVED':'ABSENT'};
      if(role==='event')fields={...fields,responsibility:texts,execution_authority_version_pk:target?.execution_authority_version_pk??null,authority_reference_state:target?'RESOLVED':ref?'UNRESOLVED':'ABSENT'};
      if(role==='outcome')fields={...fields,experience:texts,terminal:tags['outcome-terminal']?.includes(true)??false,terminal_disposition:one(tags,'terminal-disposition')};
      ds.definition(ident,{owner_definition_digest:d.definition_digest.toString('hex'),role,id,text:texts,declared_reference:ref,...(target?{target_definition_digest:target.definition_digest.toString('hex')}:{})},fields,[o],{table:'scenario_'+role,pk:{scenario_version_pk:d.scenario_version_pk}});
      if(ref&&!target){const ro=ds.observation(a.appearance,`/line/${s.location.line}/reference/${role}`,'RELATIONSHIP',ref,{role:role==='input'?'INPUT_CONTRACT':'EVENT_AUTHORITY',source:s.name,target:ref});ds.issues.push({code:'REFERENCE_UNRESOLVED',message:'Declared '+role+' reference did not resolve in the captured capability authority.',observation:ro,referenceRole:role==='input'?'INPUT_CONTRACT':'EVENT_AUTHORITY'});}
    }
    const oc=contracts.get(one(tags,'outcome-contract'));if(oc&&one(tags,'outcome'))ds.member('scenario_outcome_contract',{scenario_version_pk:d.scenario_version_pk,contract_version_pk:oc.contract_version_pk},d,'/semantics/tags/outcome-contract',[o]);
  }
  const conditions=new Map();
  for(const [i,c]of (cj.experience?.observableConditions??[]).entries()){if(!validId(c.conditionId))continue;const o=obs(ca,`/experience/observableConditions/${i}`,c,'OBSERVABLE_CONDITION',c.conditionId),ident=ds.identity('OBSERVABLE_CONDITION',c.conditionId,ds.ownedNamespace('OBSERVABLE_CONDITION',cap));const cd=ds.definition(ident,{owner_definition_digest:cap.definition_digest.toString('hex'),condition:c},{owner_definition_pk:cap.semantic_object_definition_pk,condition_id:c.conditionId,statement:c.statement??null},[o],{table:'observable_condition'});conditions.set(c.conditionId,{d:cd,o});}
  const graph=exact('semantic-graph.authority.json');if(Array.isArray(graph?.json?.transitions)){
   const variants=new Map();for(const [i,v]of (graph.json.scenarioOutcomes??[]).entries()){const s=scenarios.get(v.scenarioId);if(!s||!one(s.tags,'outcome'))continue;const o=obs(graph,`/scenarioOutcomes/${i}`,v,'OUTCOME_VARIANTS');for(const [j,id]of (v.variants??[]).entries()){if(!validId(id))continue;const variant=ds.member('outcome_variant',{scenario_version_pk:s.d.scenario_version_pk,variant_id:id,terminal:null},s.d,'/graph/variants/'+pointer(id),[o]);variants.set(v.scenarioId+'\0'+id,variant);}}
   for(const [i,t]of graph.json.transitions.entries()){const o=ds.observation(graph.appearance,`/transitions/${i}`,'RELATIONSHIP',t,{role:'SEMANTIC_GRAPH_TRANSITION',source:t.from?.scenarioId??null,target:t.to?.scenarioId??null});ds.add('observed_semantic_graph_transition',{source_observation_pk:o.source_observation_pk,transition_id:validId(t.transitionId)?t.transitionId:null,from_scenario_ref:t.from?.scenarioId??null,from_outcome_ref:t.from?.outcomeId??null,to_scenario_ref:t.to?.scenarioId??null,to_input_ref:t.to?.inputId??null,declared_topology:validId(t.topologyKind)?t.topologyKind:null,declared_progress:validId(t.semanticProgress)?t.semanticProgress:null,selected_variant_ref:t.selectsVariant??null});const from=scenarios.get(t.from?.scenarioId),to=scenarios.get(t.to?.scenarioId),variant=variants.get(t.from?.scenarioId+'\0'+t.selectsVariant);if(from&&to&&one(from.tags,'outcome')===t.from?.outcomeId&&one(to.tags,'input')===t.to?.inputId&&(!t.selectsVariant||variant))ds.add('observed_transition_resolution',{estate_model_pk:ds.model.estate_model_pk,source_observation_pk:o.source_observation_pk,source_scenario_version_pk:from.d.scenario_version_pk,target_scenario_version_pk:to.d.scenario_version_pk,selecting_variant_pk:variant?.outcome_variant_pk??null});else ds.issues.push({code:'TRANSITION_REFERENCE_UNRESOLVED',message:'Observed transition endpoints do not resolve to exact declared scenario faces and variant.',observation:o,referenceRole:'SEMANTIC_GRAPH_TRANSITION'});}
   graph.family='OBSERVED_SEMANTIC_GRAPH';if(!(graph.json.edgeGroups?.length))mark(graph,'OBSERVED_SEMANTIC_GRAPH');
  }
  const fa=exact('fixtures.authority.json');if(fa?.json?.fixtureType==='consumer-capability-fixtures.v1'){
   let complete=true;const ids=new Set();for(const [i,x]of fa.json.fixtures.entries()){if(!validId(x.fixtureId)||ids.has(x.fixtureId)||!Object.hasOwn(x,'input')){complete=false;issue(fa,'FIXTURE_DECLARATION_UNRESOLVED','Fixture requires one distinct ID and explicit input.',`/fixtures/${i}`);continue;}ids.add(x.fixtureId);const o=obs(fa,`/fixtures/${i}`,x,'FIXTURE',x.fixtureId),ident=ds.identity('FIXTURE',x.fixtureId,ds.ownedNamespace('FIXTURE',cap));const def=ds.definition(ident,{owner_definition_digest:cap.definition_digest.toString('hex'),fixture:x},{owner_definition_pk:cap.semantic_object_definition_pk,fixture_id:x.fixtureId,fixture_profile:'consumer-capability-fixtures.v1'},[o],{table:'fixture'});const expected=x.expected??{},terminal=scenarios.get(expected.terminalScenarioId);const c=ds.member('fixture_case',{fixture_pk:def.fixture_pk,case_id:null,ordinal:0,input_content_pk:ds.json(x.input).content_object_pk,expected_disposition:expected.disposition??null,terminal_scenario_version_pk:terminal?.d.scenario_version_pk??null},def,'/semantics/fixture',[o]);
    for(const [j,a]of (expected.outcomeAssertions??[]).entries()){if(!validId(a.operator)||typeof a.path!=='string'||!Object.hasOwn(a,'value')){complete=false;continue;}const ptr=`/semantics/fixture/expected/outcomeAssertions/${j}`,as=ds.member('fixture_assertion',{fixture_case_pk:c.fixture_case_pk,ordinal:j,condition_id:a.conditionId??null,path:a.path,operator:a.operator,expected_value_content_pk:ds.json(a.value).content_object_pk},def,ptr,[o]);
     // An assertion's conditionId references a condition declared by the capability that owns this fixture. A reference alone never declares the condition.
     if(validId(a.conditionId)){const target=conditions.get(a.conditionId);
      if(target)ds.member('fixture_assertion_condition',{fixture_assertion_pk:as.fixture_assertion_pk,observable_condition_pk:target.d.observable_condition_pk},def,ptr+'/conditionId',[o,target.o]);
      // The assertion's literal test data stays complete. An unresolved condition reference is recorded separately and never invents the condition definition.
      else{const ro=ds.observation(fa.appearance,`/fixtures/${i}/expected/outcomeAssertions/${j}/conditionId`,'RELATIONSHIP',a.conditionId,{role:'ASSERTION_CONDITION',source:x.fixtureId,target:a.conditionId});ds.issues.push({code:'REFERENCE_UNRESOLVED',message:'Assertion condition reference does not resolve to an observable condition declared by the owning capability.',observation:ro,referenceRole:'ASSERTION_CONDITION'});}}
    }
    for(const [j,id]of (expected.scenarioSequence??[]).entries()){const s=scenarios.get(id);if(s)ds.member('fixture_scenario_step',{fixture_case_pk:c.fixture_case_pk,ordinal:j,scenario_version_pk:s.d.scenario_version_pk},def,`/semantics/fixture/expected/scenarioSequence/${j}`,[o]);else{complete=false;issue(fa,'FIXTURE_SCENARIO_UNRESOLVED','Fixture scenario reference does not resolve in its capability.',`/fixtures/${i}/expected/scenarioSequence/${j}`,'SCENARIO_REFERENCE',id);}}
    for(const [id,value]of Object.entries(x.portOutcomes??{})){const p=ports.get(id);if(p)ds.member('fixture_port_outcome',{fixture_case_pk:c.fixture_case_pk,port_version_pk:p.port_version_pk,ordinal:0,content_object_pk:ds.json(value).content_object_pk},def,'/semantics/fixture/portOutcomes/'+pointer(id),[o]);else{complete=false;issue(fa,'FIXTURE_PORT_UNRESOLVED','Fixture outcome selector is not a declared port in this capability; no Port was invented.',`/fixtures/${i}/portOutcomes/${pointer(id)}`,'PORT_REFERENCE',id);}}
   }if(complete)mark(fa,'FIXTURE');else fa.family='PARTIAL_FIXTURE';
  }
 }
 for(const a of artifacts.filter(a=>a.sourcePath==='authority/cli/provider-catalog.json'&&a.json?.catalogType==='sfx-provider-catalog.v1')){for(const [i,p]of a.json.providers.entries()){if(!validId(p.providerId)){issue(a,'PROVIDER_ID_REQUIRED','Provider has no valid declared providerId.',`/providers/${i}`);continue;}const ident=ds.identity('PROVIDER',p.providerId,namespace('PROVIDER',mapping.namespaceBindings.PROVIDER)),o=obs(a,`/providers/${i}`,p,'PROVIDER',p.providerId);ds.definition(ident,p,{name:p.name??null,declaration_profile:'sfx-provider-catalog.v1'},[o]);}a.family='PARTIAL_PROVIDER_CATALOG';}
 // Every appearance remains accounted for, including unsupported semantic profiles.
 for(const a of artifacts){ds.add('source.source_classification',{source_appearance_pk:a.appearance.source_appearance_pk,mapping_rule_pk:ds.rule.mapping_rule_pk,family_code:a.family,classification_state:a.classification});if(a.classification==='UNSUPPORTED')issue(a,a.parseError?'SOURCE_JSON_UNSUPPORTED':'SOURCE_PROFILE_UNSUPPORTED',a.parseError??'This source profile is preserved but has no complete mapping in the initial normalized inspection model.');}
 const irc=ds.json({rule:'inspection-mapping-coverage.v1',mapping_digest:rc.content_digest.toString('hex')});const ir=ds.add('analysis.integrity_rule',{rule_id:'inspection-mapping-coverage.v1',rule_digest:irc.content_digest,layer:1,rule_content_pk:irc.content_object_pk});
 const now=new Date(),inputs=ds.rows.get('source.source_observation').map(o=>o.source_observation_pk);
 const assessment=ds.add('analysis.assessment',{estate_model_pk:ds.model.estate_model_pk,integrity_rule_pk:ir.integrity_rule_pk,assessment_kind:'INTEGRITY',scope_digest:ds.snapshot.snapshot_digest,input_set_digest:bytesDigest(canonical(inputs)),evaluation_state:'EVALUATED',evaluated_at:now});
 for(const pk of inputs)ds.add('analysis.assessment_source_input',{assessment_pk:assessment.assessment_pk,source_observation_pk:pk,role:'MAPPING_INPUT'});
 for(const x of ds.issues){const f=ds.add('analysis.integrity_finding',{assessment_pk:assessment.assessment_pk,finding_digest:bytesDigest(canonical({code:x.code,observation:x.observation.source_observation_pk,message:x.message})),finding_code:x.code,severity:'WARNING',source_observation_pk:x.observation.source_observation_pk,subject_definition_pk:null,expected_content_pk:null,observed_content_pk:null,message:x.message},{dedup:true});if(x.referenceRole)ds.add('analysis.unresolved_reference',{estate_model_pk:ds.model.estate_model_pk,source_observation_pk:x.observation.source_observation_pk,reference_role:x.referenceRole,resolution_state:'MISSING_TARGET',finding_pk:f.integrity_finding_pk});}
 for(const family of [...new Set(artifacts.map(a=>a.family))].sort()){const xs=artifacts.filter(a=>a.family===family),count=s=>xs.filter(a=>a.classification===s).length;const a=ds.add('analysis.assessment',{estate_model_pk:ds.model.estate_model_pk,integrity_rule_pk:ir.integrity_rule_pk,assessment_kind:'COVERAGE',scope_digest:bytesDigest(family),input_set_digest:bytesDigest(canonical(xs.map(a=>a.artifactId).sort())),evaluation_state:'EVALUATED',evaluated_at:now});ds.add('analysis.coverage_assessment',{assessment_pk:a.assessment_pk,assessment_kind:'COVERAGE',source_profile:family,count_unit:'APPEARANCE',total_count:xs.length,normalized_count:count('SUPPORTED'),unresolved_count:count('AMBIGUOUS'),unsupported_count:count('UNSUPPORTED'),outside_count:count('OUTSIDE_SCOPE')});}
 ds.summary={snapshot:snapshot.snapshotId,manifest:ds.model.mapping_manifest_digest.toString('hex'),counts:ds.counts(),coverage:{total:artifacts.length,normalized:artifacts.filter(a=>a.classification==='SUPPORTED').length,unsupported:artifacts.filter(a=>a.classification==='UNSUPPORTED').length,outside:artifacts.filter(a=>a.classification==='OUTSIDE_SCOPE').length},findings:ds.issues.length};return ds;
}
if(process.argv[1]===fileURLToPath(import.meta.url))try{console.log(JSON.stringify((await normalize()).summary,null,2));}catch(e){console.error(e.stack);process.exitCode=1;}
