import { tables, families, owned, q, fq, digest, validateCatalog } from './catalog.mjs';

const prefix=(a,b)=>a.length<=b.length&&a.every((c,i)=>c===b[i]);
const key=(t,c)=>t.columns[c].token==='PTR'?c+'_key':c;
const keys=(t,cs)=>cs.map(c=>q(key(t,c))).join(',');
const name=(kind,t,body)=>q(`${kind}_${t.name.replace('.','_')}_${digest(body).slice(0,12)}`);
const sqlError=(code,msg)=>`THROW ${code}, '${msg}', 1;`;
const fail=(condition,msg)=>`IF EXISTS (${condition}) ${sqlError(51001,msg)}`;
const inModel=(alias,column='_owner_definition_pk')=>`EXISTS (SELECT 1 FROM model.estate_definition ed WHERE ed.estate_model_pk=@estate_model_pk AND ed.semantic_object_definition_pk=${alias}.${q(column)})`;
export function tableBatches(){
  validateCatalog();const out=[];
  for(const schema of ['source','model','analysis','sidefx'])out.push(`IF SCHEMA_ID('${schema}') IS NULL EXEC('CREATE SCHEMA ${q(schema)} AUTHORIZATION dbo');`);
  for(const t of tables.values()){
    const cols=[];
    for(const [c,s]of Object.entries(t.columns)){
      cols.push(`${q(c)} ${s.type}${t.identity&&t.pk.length===1&&t.pk[0]===c&&s.token==='K'?' IDENTITY(1,1)':''} ${s.nullable?'NULL':'NOT NULL'}`);
      if(s.token==='PTR')cols.push(`${q(c+'_key')} AS CONVERT(varbinary(800),${q(c)}) PERSISTED`);
      if(s.token==='N')t.checks.includes(`${q(c)}>=0`)||t.checks.push(`${q(c)}>=0`);
      if(s.token==='ID'){
        const check=`${s.nullable?`${q(c)} IS NULL OR `:''}(DATALENGTH(${q(c)})>0 AND DATALENGTH(${q(c)})=DATALENGTH(LTRIM(RTRIM(${q(c)}))) AND UNICODE(LEFT(${q(c)},1)) NOT IN(9,10,13) AND UNICODE(RIGHT(${q(c)},1)) NOT IN(9,10,13))`;
        if(!t.checks.includes(check))t.checks.push(check);
      }
    }
    cols.push(`CONSTRAINT ${name('PK',t,t.pk.join())} PRIMARY KEY CLUSTERED (${keys(t,t.pk)})`);
    for(const a of t.aks)cols.push(`CONSTRAINT ${name('AK',t,a.join())} UNIQUE NONCLUSTERED (${keys(t,a)})`);
    for(const c of t.checks)cols.push(`CONSTRAINT ${name('CK',t,c)} CHECK (${c})`);
    out.push(`CREATE TABLE ${fq(t.name)} (\n  ${cols.join(',\n  ')}\n);`);
  }
  for(const t of tables.values()){
    for(const f of t.fks){const target=tables.get(f.target);out.push(`ALTER TABLE ${fq(t.name)} WITH CHECK ADD CONSTRAINT ${name('FK',t,JSON.stringify(f))} FOREIGN KEY (${keys(t,f.cols)}) REFERENCES ${fq(f.target)} (${keys(target,f.targetCols)}) ON UPDATE NO ACTION ON DELETE NO ACTION;`);}
    for(const f of t.filtered)out.push(`CREATE UNIQUE NONCLUSTERED INDEX ${name('UXF',t,JSON.stringify(f))} ON ${fq(t.name)} (${keys(t,f.cols)}) WHERE ${f.where};`);
    const indexes=[t.pk,...t.aks];
    for(const ix of [...t.indexes,...t.fks.map(f=>f.cols)])if(!indexes.some(existing=>prefix(ix,existing))){out.push(`CREATE NONCLUSTERED INDEX ${name('IX',t,ix.join())} ON ${fq(t.name)} (${keys(t,ix)});`);indexes.push(ix);}
  }
  return out;
}

export function gateBatches(){
  const out=[];
  const defs=[...families.map(f=>'model.'+f.version),...owned.map(o=>o.table)];
  const identities=[...families.map(f=>'model.'+f.name),...owned.map(o=>o.table)];
  out.push(`CREATE VIEW source.v_definition_witness AS ${defs.map(n=>`SELECT semantic_object_definition_pk,semantic_object_pk,object_kind FROM ${fq(n)}`).join(' UNION ALL ')};`);
  out.push(`CREATE VIEW source.v_identity_witness AS ${identities.map(n=>`SELECT DISTINCT semantic_object_pk,object_kind FROM ${fq(n)}`).join(' UNION ')};`);
  const members=[...tables.values()].filter(t=>t.owner);
  out.push(`CREATE VIEW source.v_normalized_member AS ${members.map(t=>`SELECT _owner_definition_pk,CAST('${t.name.split('.').at(-1)}' AS varchar(64)) COLLATE Latin1_General_100_BIN2 member_kind,_canonical_pointer_key FROM ${fq(t.name)}`).join(' UNION ALL ')};`);
  const checks=[];
  checks.push(fail(`SELECT 1 FROM source.estate_model WHERE estate_model_pk=@estate_model_pk AND publication_state<>'BUILDING'`,'MODEL_NOT_BUILDING'));
  checks.push(`IF NOT EXISTS(SELECT 1 FROM source.estate_model WHERE estate_model_pk=@estate_model_pk) ${sqlError(51001,'MODEL_NOT_FOUND')}`);
  checks.push(`IF NOT EXISTS(SELECT 1 FROM source.estate_model_rule WHERE estate_model_pk=@estate_model_pk) ${sqlError(51001,'G_PUBLISH_MAPPING_REQUIRED')}`);
  checks.push(fail(`SELECT 1 FROM source.mapping_rule r JOIN source.content_object c ON c.content_object_pk=r.rule_content_object_pk WHERE r.rule_digest<>c.content_digest`,'G_CONTENT_MAPPING_RULE'));
  checks.push(fail(`SELECT 1 FROM source.source_observation o JOIN source.source_appearance a ON a.source_appearance_pk=o.source_appearance_pk JOIN source.estate_model m ON m.estate_snapshot_pk=a.estate_snapshot_pk WHERE m.estate_model_pk=@estate_model_pk AND o.locator_digest<>HASHBYTES('SHA2_256',CONVERT(varchar(max),o.locator COLLATE Latin1_General_100_BIN2_UTF8))`,'G_CONTENT_LOCATOR'));
  checks.push(fail(`SELECT 1 FROM source.source_observation o JOIN source.source_appearance a ON a.source_appearance_pk=o.source_appearance_pk JOIN source.estate_model m ON m.estate_snapshot_pk=a.estate_snapshot_pk WHERE m.estate_model_pk=@estate_model_pk AND ((o.observation_kind='DECLARATION' AND NOT EXISTS(SELECT 1 FROM source.declaration_observation d WHERE d.source_observation_pk=o.source_observation_pk)) OR (o.observation_kind='RELATIONSHIP' AND NOT EXISTS(SELECT 1 FROM source.relationship_observation r WHERE r.source_observation_pk=o.source_observation_pk)))`,'G_OBSERVATION_SUBTYPE'));
  checks.push(fail(`SELECT 1 FROM model.estate_definition ed JOIN model.semantic_object_definition d ON d.semantic_object_definition_pk=ed.semantic_object_definition_pk OUTER APPLY (SELECT COUNT_BIG(*) n FROM source.v_definition_witness w WHERE w.semantic_object_definition_pk=d.semantic_object_definition_pk AND w.semantic_object_pk=d.semantic_object_pk AND w.object_kind=d.object_kind) w WHERE ed.estate_model_pk=@estate_model_pk AND w.n<>1`,'G_SUBTYPE_DEFINITION'));
  checks.push(fail(`SELECT 1 FROM model.estate_definition ed JOIN model.semantic_object_definition d ON d.semantic_object_definition_pk=ed.semantic_object_definition_pk WHERE ed.estate_model_pk=@estate_model_pk AND NOT EXISTS(SELECT 1 FROM source.v_identity_witness w WHERE w.semantic_object_pk=d.semantic_object_pk AND w.object_kind=d.object_kind)`,'G_SUBTYPE_IDENTITY'));
  checks.push(fail(`SELECT 1 FROM model.estate_definition ed JOIN model.semantic_object_definition d ON d.semantic_object_definition_pk=ed.semantic_object_definition_pk JOIN source.content_object c ON c.content_object_pk=d.canonical_content_pk WHERE ed.estate_model_pk=@estate_model_pk AND (d.definition_digest<>c.content_digest OR ISJSON(CONVERT(varchar(max),c.content_bytes) COLLATE Latin1_General_100_BIN2_UTF8)<>1)`,'G_CONTENT_DEFINITION'));
  checks.push(fail(`SELECT 1 FROM model.schema_object s JOIN source.content_object c ON c.content_object_pk=s.content_object_pk WHERE s.content_digest<>c.content_digest`,'G_CONTENT_SCHEMA'));
  checks.push(fail(`SELECT 1 FROM model.binding_context b JOIN source.content_object c ON c.content_object_pk=b.canonical_content_pk WHERE b.context_digest<>c.content_digest`,'G_CONTENT_CONTEXT'));
  checks.push(fail(`SELECT 1 FROM model.semantic_object o JOIN model.identity_namespace n ON n.namespace_pk=o.namespace_pk WHERE n.namespace_kind<>o.object_kind AND EXISTS(SELECT 1 FROM model.semantic_object_definition d JOIN model.estate_definition ed ON ed.semantic_object_definition_pk=d.semantic_object_definition_pk WHERE ed.estate_model_pk=@estate_model_pk AND d.semantic_object_pk=o.semantic_object_pk)`,'G_NAMESPACE_KIND'));
  checks.push(fail(`SELECT 1 FROM model.scenario s JOIN model.capability c ON c.capability_pk=s.capability_pk WHERE EXISTS(SELECT 1 FROM model.scenario_version v JOIN model.estate_definition ed ON ed.semantic_object_definition_pk=v.semantic_object_definition_pk WHERE ed.estate_model_pk=@estate_model_pk AND v.scenario_pk=s.scenario_pk) AND NOT EXISTS(SELECT 1 FROM model.namespace_owner n WHERE n.namespace_pk=s.namespace_pk AND n.owner_semantic_object_pk=c.semantic_object_pk AND n.scope_kind='SCENARIO')`,'G_NAMESPACE_SCENARIO_OWNER'));
  for(const n of ['scenario_input','scenario_event','scenario_outcome'])checks.push(fail(`SELECT 1 FROM model.${n} f JOIN model.scenario_version v ON v.scenario_version_pk=f.scenario_version_pk JOIN model.scenario s ON s.scenario_pk=v.scenario_pk WHERE ${inModel('f')} AND NOT EXISTS(SELECT 1 FROM model.namespace_owner n WHERE n.namespace_pk=f.namespace_pk AND n.owner_semantic_object_pk=s.semantic_object_pk AND n.scope_kind=f.object_kind)`,'G_NAMESPACE_FACE_OWNER'));
  for(const n of ['fixture','observable_condition','proof_obligation'])checks.push(fail(`SELECT 1 FROM model.${n} f JOIN model.semantic_object_definition d ON d.semantic_object_definition_pk=f.owner_definition_pk WHERE ${inModel('f')} AND NOT EXISTS(SELECT 1 FROM model.namespace_owner n WHERE n.namespace_pk=f.namespace_pk AND n.owner_semantic_object_pk=d.semantic_object_pk AND n.scope_kind=f.object_kind)`,'G_NAMESPACE_'+n.toUpperCase()+'_OWNER'));
  for(const n of ['c4_context','c4_container','c4_component'])checks.push(fail(`SELECT 1 FROM model.${n} f JOIN model.blueprint_version v ON v.blueprint_version_pk=f.blueprint_version_pk WHERE ${inModel('f')} AND NOT EXISTS(SELECT 1 FROM model.namespace_owner n WHERE n.namespace_pk=f.namespace_pk AND n.owner_semantic_object_pk=v.semantic_object_pk AND n.scope_kind=f.object_kind)`,'G_NAMESPACE_'+n.toUpperCase()+'_OWNER'));
  checks.push(`;WITH ancestry AS (SELECT o.semantic_object_pk,0 depth FROM model.semantic_object o WHERE NOT EXISTS(SELECT 1 FROM model.namespace_owner n WHERE n.namespace_pk=o.namespace_pk) UNION ALL SELECT o.semantic_object_pk,p.depth+1 FROM ancestry p JOIN model.namespace_owner n ON n.owner_semantic_object_pk=p.semantic_object_pk JOIN model.semantic_object o ON o.namespace_pk=n.namespace_pk) SELECT semantic_object_pk INTO #namespace_roots FROM ancestry OPTION(MAXRECURSION 32767); ${fail(`SELECT 1 FROM model.semantic_object_definition d JOIN model.estate_definition ed ON ed.semantic_object_definition_pk=d.semantic_object_definition_pk WHERE ed.estate_model_pk=@estate_model_pk AND NOT EXISTS(SELECT 1 FROM #namespace_roots r WHERE r.semantic_object_pk=d.semantic_object_pk)`,'G_NAMESPACE_OWNER_CYCLE')} DROP TABLE #namespace_roots;`);
  for(const t of members){
    const owner=t.owner;
    const mismatch=owner.self?`SELECT 1 FROM ${fq(t.name)} r WHERE ${inModel('r')} AND r._owner_definition_pk<>r.semantic_object_definition_pk`:`SELECT 1 FROM ${fq(t.name)} r JOIN ${fq(owner.parent)} p ON p.${q(tables.get(owner.parent).pk[0])}=r.${q(owner.column)} WHERE ${inModel('r')} AND r._owner_definition_pk<>p.${q(owner.target)}`;
    checks.push(fail(mismatch,'G_OWNER_'+t.name.split('.').at(-1)));
  }
  checks.push(fail(`SELECT 1 FROM source.v_normalized_member r WHERE ${inModel('r')} AND NOT EXISTS(SELECT 1 FROM source.source_lineage l JOIN source.source_observation o ON o.source_observation_pk=l.source_observation_pk JOIN source.source_appearance a ON a.source_appearance_pk=o.source_appearance_pk JOIN source.estate_model m ON m.estate_snapshot_pk=a.estate_snapshot_pk AND m.estate_model_pk=@estate_model_pk JOIN source.estate_model_rule mr ON mr.estate_model_pk=m.estate_model_pk AND mr.mapping_rule_pk=l.mapping_rule_pk WHERE l.semantic_object_definition_pk=r._owner_definition_pk AND l.member_kind=r.member_kind AND l.canonical_pointer_key=r._canonical_pointer_key)`,'G_LINEAGE_MEMBER'));
  checks.push(fail(`SELECT 1 FROM source.source_lineage l WHERE ${inModel('l','semantic_object_definition_pk')} AND NOT EXISTS(SELECT 1 FROM source.v_normalized_member r WHERE r._owner_definition_pk=l.semantic_object_definition_pk AND r.member_kind=l.member_kind AND r._canonical_pointer_key=l.canonical_pointer_key)`,'G_LINEAGE_DANGLING'));
  const defTables=new Map(defs.map(n=>[n,'semantic_object_definition_pk']));defTables.set('model.semantic_object_definition','semantic_object_definition_pk');
  for(const t of members)for(const f of t.fks)if(defTables.has(f.target)&&f.cols[0]!=='_owner_definition_pk'){
    const join=f.cols.map((c,i)=>`r.${q(c)}=p.${q(f.targetCols[i])}`).join(' AND ');
    checks.push(fail(`SELECT 1 FROM ${fq(t.name)} r JOIN ${fq(f.target)} p ON ${join} WHERE ${inModel('r')} AND NOT EXISTS(SELECT 1 FROM model.estate_definition ed WHERE ed.estate_model_pk=@estate_model_pk AND ed.semantic_object_definition_pk=p.semantic_object_definition_pk)`,'G_ESTATE_CLOSURE_'+t.name.split('.').at(-1)));
  }
  checks.push(fail(`SELECT 1 FROM model.execution_operation o WHERE ${inModel('o')} AND ((o.operation_kind='invoke-port' AND NOT EXISTS(SELECT 1 FROM model.operation_port_invocation p WHERE p.execution_operation_pk=o.execution_operation_pk)) OR (o.operation_kind='invoke-scenario' AND NOT EXISTS(SELECT 1 FROM model.operation_scenario_invocation p WHERE p.execution_operation_pk=o.execution_operation_pk)) OR (o.operation_kind='project-state' AND NOT EXISTS(SELECT 1 FROM model.operation_state_projection p WHERE p.execution_operation_pk=o.execution_operation_pk)) OR o.operation_kind NOT IN('invoke-port','invoke-scenario','project-state'))`,'G_EXECUTION_SUBTYPE'));
  checks.push(fail(`SELECT 1 FROM model.transformation_version v WHERE ${inModel('v')} AND NOT EXISTS(SELECT 1 FROM model.transformation_root r WHERE r.transformation_version_pk=v.transformation_version_pk)`,'G_EXPRESSION_ROOT'));
  checks.push(fail(`SELECT 1 FROM model.transformation_root r JOIN model.transformation_expression_child c ON c.child_node_pk=r.expression_node_pk WHERE ${inModel('r')}`,'G_EXPRESSION_ROOT_PARENT'));
  checks.push(fail(`SELECT 1 FROM model.transformation_expression_node n WHERE ${inModel('n')} AND NOT EXISTS(SELECT 1 FROM model.transformation_root r WHERE r.expression_node_pk=n.expression_node_pk) AND NOT EXISTS(SELECT 1 FROM model.transformation_expression_child c WHERE c.child_node_pk=n.expression_node_pk)`,'G_EXPRESSION_DISCONNECTED'));
  checks.push(`;WITH reachable AS (SELECT r.transformation_version_pk,r.expression_node_pk FROM model.transformation_root r WHERE ${inModel('r')} UNION ALL SELECT c.transformation_version_pk,c.child_node_pk FROM reachable r JOIN model.transformation_expression_child c ON c.parent_node_pk=r.expression_node_pk) SELECT DISTINCT expression_node_pk INTO #reachable FROM reachable OPTION(MAXRECURSION 32767); ${fail(`SELECT 1 FROM model.transformation_expression_node n WHERE ${inModel('n')} AND NOT EXISTS(SELECT 1 FROM #reachable r WHERE r.expression_node_pk=n.expression_node_pk)`,'G_EXPRESSION_CYCLE_OR_UNREACHABLE')} DROP TABLE #reachable;`);
  checks.push(fail(`SELECT 1 FROM model.transformation_expression_child c JOIN model.transformation_expression_node p ON p.expression_node_pk=c.parent_node_pk WHERE ${inModel('c')} AND ((c.member_kind='ARRAY_MEMBER' AND p.node_kind<>'ARRAY') OR (c.member_kind='OBJECT_MEMBER' AND p.node_kind NOT IN ('OBJECT','OPERATOR')))`,'G_EXPRESSION_PARENT_KIND'));
  checks.push(fail(`SELECT 1 FROM model.transformation_expression_child c WHERE ${inModel('c')} AND c.member_kind='ARRAY_MEMBER' GROUP BY c.parent_node_pk HAVING MIN(c.ordinal)<>0 OR MAX(c.ordinal)+1<>COUNT_BIG(*)`,'G_EXPRESSION_ARRAY_ORDINALS'));
  checks.push(fail(`SELECT 1 FROM model.blueprint_node_face f JOIN model.blueprint_node n ON n.blueprint_node_pk=f.blueprint_node_pk WHERE ${inModel('f')} AND n.altitude='CAPABILITY' AND ((f.position='FIRST' AND f.expected_kind<>'SCENARIO_INPUT') OR (f.position='ENERGIZED' AND f.expected_kind<>'SCENARIO_EVENT') OR (f.position='RESULT' AND f.expected_kind NOT IN('SCENARIO_OUTCOME','PRODUCT')))`,'G_GEOMETRY_FACE_KIND'));
  for(const n of ['scenario_input','scenario_event','scenario_outcome'])checks.push(fail(`SELECT 1 FROM model.blueprint_node_face f JOIN model.${n} s ON s.semantic_object_definition_pk=f.semantic_object_definition_pk JOIN model.blueprint_node_scenario ns ON ns.blueprint_node_pk=f.blueprint_node_pk WHERE ${inModel('f')} AND s.scenario_version_pk<>ns.scenario_version_pk`,'G_GEOMETRY_FACE_SCENARIO'));
  checks.push(fail(`SELECT 1 FROM model.blueprint_edge e WHERE ${inModel('e')} AND ((e.contract_relation IS NOT NULL AND NOT EXISTS(SELECT 1 FROM model.blueprint_edge_contract c WHERE c.blueprint_edge_pk=e.blueprint_edge_pk)) OR (e.topology_role='BOUNDED_RETURN' AND NOT EXISTS(SELECT 1 FROM model.blueprint_bounded_return b WHERE b.blueprint_edge_pk=e.blueprint_edge_pk)) OR (e.topology_role='FAN_OUT_MEMBER' AND NOT EXISTS(SELECT 1 FROM model.blueprint_fan_out_member f WHERE f.blueprint_edge_pk=e.blueprint_edge_pk)))`,'G_GEOMETRY_REQUIRED_EXTENSION'));
  checks.push(fail(`SELECT 1 FROM model.blueprint_bounded_return b JOIN model.blueprint_edge e ON e.blueprint_edge_pk=b.blueprint_edge_pk WHERE ${inModel('b')} AND e.topology_role<>'BOUNDED_RETURN'`,'G_GEOMETRY_RETURN_KIND'));
  checks.push(fail(`SELECT 1 FROM model.blueprint_fan_out_member b JOIN model.blueprint_edge e ON e.blueprint_edge_pk=b.blueprint_edge_pk WHERE ${inModel('b')} AND e.topology_role<>'FAN_OUT_MEMBER'`,'G_GEOMETRY_FANOUT_KIND'));
  checks.push(fail(`SELECT 1 FROM model.blueprint_convergence_requirement r JOIN model.blueprint_node n ON n.blueprint_node_pk=r.convergence_node_pk WHERE ${inModel('r')} AND n.node_kind<>'convergence'`,'G_GEOMETRY_CONVERGENCE_KIND'));
  checks.push(fail(`SELECT 1 FROM model.blueprint_edge e JOIN model.blueprint_node f ON f.blueprint_node_pk=e.from_node_pk JOIN model.blueprint_node t ON t.blueprint_node_pk=e.to_node_pk WHERE ${inModel('e')} AND ((e.topology_role<>'ALTITUDE_DESCENT' AND f.altitude<>t.altitude) OR (e.topology_role='ALTITUDE_DESCENT' AND CASE f.altitude WHEN 'CAPABILITY' THEN 0 WHEN 'OPERATION' THEN 1 WHEN 'MECHANIC' THEN 2 ELSE 3 END >= CASE t.altitude WHEN 'CAPABILITY' THEN 0 WHEN 'OPERATION' THEN 1 WHEN 'MECHANIC' THEN 2 ELSE 3 END))`,'G_GEOMETRY_ALTITUDE'));
  checks.push(fail(`SELECT 1 FROM model.blueprint_edge_contract c JOIN model.blueprint_edge e ON e.blueprint_edge_pk=c.blueprint_edge_pk WHERE ${inModel('c')} AND (NOT EXISTS(SELECT 1 FROM model.blueprint_node_scenario n WHERE n.blueprint_node_pk=e.to_node_pk AND n.scenario_version_pk=c.downstream_scenario_version_pk) OR NOT EXISTS(SELECT 1 FROM model.blueprint_node_scenario n JOIN model.outcome_product p ON p.scenario_version_pk=n.scenario_version_pk WHERE n.blueprint_node_pk=e.from_node_pk AND p.product_definition_pk=c.product_definition_pk) AND NOT EXISTS(SELECT 1 FROM model.outcome_variant_product p WHERE p.outcome_variant_pk=e.selecting_variant_pk AND p.product_definition_pk=c.product_definition_pk))`,'G_GEOMETRY_CONTRACT_ENDPOINT'));
  for(const target of ['port','mechanic'])checks.push(fail(`SELECT 1 FROM model.provider_binding b JOIN model.slot_${target}_requirement r ON r.provider_slot_pk=b.provider_slot_pk WHERE ${inModel('b')} AND NOT EXISTS(SELECT 1 FROM model.binding_${target}_implementation i WHERE i.provider_binding_pk=b.provider_binding_pk AND i.slot_${target}_requirement_pk=r.slot_${target}_requirement_pk)`,'G_BINDING_'+target.toUpperCase()+'_COVERAGE'));
  checks.push(fail(`SELECT 1 FROM analysis.assessment a WHERE a.estate_model_pk=@estate_model_pk AND ((a.assessment_kind='COMPATIBILITY' AND NOT EXISTS(SELECT 1 FROM analysis.compatibility_assessment x WHERE x.assessment_pk=a.assessment_pk)) OR (a.assessment_kind='COVERAGE' AND NOT EXISTS(SELECT 1 FROM analysis.coverage_assessment x WHERE x.assessment_pk=a.assessment_pk)) OR (a.assessment_kind='CIRCUIT' AND NOT EXISTS(SELECT 1 FROM analysis.circuit_assessment x WHERE x.assessment_pk=a.assessment_pk)) OR (a.assessment_kind='PROVIDER_QUALIFICATION' AND NOT EXISTS(SELECT 1 FROM analysis.provider_qualification_assessment x WHERE x.assessment_pk=a.assessment_pk)) OR a.assessment_kind NOT IN('INTEGRITY','COMPATIBILITY','COVERAGE','CIRCUIT','PROVIDER_QUALIFICATION'))`,'G_ASSESSMENT_SUBTYPE'));
  for(const name of ['compatibility_assessment','circuit_assessment'])checks.push(fail(`SELECT 1 FROM analysis.${name} c JOIN analysis.assessment a ON a.assessment_pk=c.assessment_pk WHERE a.estate_model_pk=@estate_model_pk AND ((a.evaluation_state<>'EVALUATED' AND c.result_code IS NOT NULL) OR (a.evaluation_state='EVALUATED' AND c.result_code IS NULL))`,'G_ASSESSMENT_RESULT_STATE'));
  checks.push(fail(`SELECT 1 FROM analysis.provider_qualification_assessment c JOIN analysis.assessment a ON a.assessment_pk=c.assessment_pk WHERE a.estate_model_pk=@estate_model_pk AND (a.evaluation_state<>'EVALUATED' OR c.effective_until<a.evaluated_at)`,'G_ASSESSMENT_QUALIFICATION'));
  checks.push(fail(`SELECT 1 FROM analysis.assessment a WHERE a.estate_model_pk=@estate_model_pk AND ((a.evaluation_state='EVALUATED' AND a.evaluated_at IS NULL) OR (a.evaluation_state<>'EVALUATED' AND a.evaluated_at IS NOT NULL))`,'G_ASSESSMENT_EVALUATION_TIME'));
  checks.push(fail(`SELECT 1 FROM analysis.assessment_definition_input i JOIN analysis.assessment a ON a.assessment_pk=i.assessment_pk WHERE a.estate_model_pk=@estate_model_pk AND NOT EXISTS(SELECT 1 FROM model.estate_definition d WHERE d.estate_model_pk=a.estate_model_pk AND d.semantic_object_definition_pk=i.semantic_object_definition_pk)`,'G_ASSESSMENT_INPUT_ESTATE'));
  checks.push(fail(`SELECT 1 FROM analysis.assessment_source_input i JOIN analysis.assessment a ON a.assessment_pk=i.assessment_pk JOIN source.source_observation o ON o.source_observation_pk=i.source_observation_pk JOIN source.source_appearance p ON p.source_appearance_pk=o.source_appearance_pk JOIN source.estate_model m ON m.estate_model_pk=a.estate_model_pk WHERE a.estate_model_pk=@estate_model_pk AND p.estate_snapshot_pk<>m.estate_snapshot_pk`,'G_ASSESSMENT_SOURCE_ESTATE'));
  checks.push(fail(`SELECT 1 FROM sys.foreign_keys WHERE (is_disabled=1 OR is_not_trusted=1) AND OBJECT_SCHEMA_NAME(parent_object_id) IN('model','source','analysis') UNION ALL SELECT 1 FROM sys.check_constraints WHERE (is_disabled=1 OR is_not_trusted=1) AND OBJECT_SCHEMA_NAME(parent_object_id) IN('model','source','analysis')`,'G_PUBLISH_UNTRUSTED_CONSTRAINT'));
  out.push(`CREATE PROCEDURE source.validate_model @estate_model_pk bigint WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; ${checks.join('\n')} END;`);
  out.push(`CREATE PROCEDURE source.publish_model @estate_model_pk bigint WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRY BEGIN TRANSACTION; DECLARE @lock int; EXEC @lock=sys.sp_getapplock @Resource='sidefx:model-write',@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=60000; IF @lock<0 THROW 51002,'MODEL_LOCK_UNAVAILABLE',1; EXEC source.validate_model @estate_model_pk; UPDATE source.estate_model SET publication_state='PUBLISHED' WHERE estate_model_pk=@estate_model_pk; UPDATE source.current_model SET estate_model_pk=@estate_model_pk WHERE singleton_id=1; IF @@ROWCOUNT=0 INSERT source.current_model(singleton_id,estate_model_pk) VALUES(1,@estate_model_pk); COMMIT; END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK; THROW; END CATCH END;`);
  for(const t of tables.values()){
    if(['source.current_model','source.estate_model'].includes(t.name))continue;
    const immutable=`IF EXISTS(SELECT 1 FROM deleted) THROW 51003,'IMMUTABLE_INSPECTION_DATA',1;`;
    let published=t.owner?`IF EXISTS(SELECT 1 FROM inserted i JOIN model.estate_definition d ON d.semantic_object_definition_pk=i._owner_definition_pk JOIN source.estate_model m ON m.estate_model_pk=d.estate_model_pk WHERE m.publication_state='PUBLISHED') THROW 51003,'PUBLISHED_DEFINITION_IMMUTABLE',1;`:t.name==='model.estate_definition'||t.name==='model.estate_capability'||t.columns.estate_model_pk?`IF EXISTS(SELECT 1 FROM inserted i JOIN source.estate_model m ON m.estate_model_pk=i.estate_model_pk WHERE m.publication_state='PUBLISHED') THROW 51003,'PUBLISHED_MEMBERSHIP_IMMUTABLE',1;`:'';
    if(t.owner&&!t.owner.self){const o=t.owner,p=tables.get(o.parent);published+=` IF EXISTS(SELECT 1 FROM inserted i JOIN ${fq(o.parent)} p ON p.${q(p.pk[0])}=i.${q(o.column)} JOIN model.estate_definition d ON d.semantic_object_definition_pk=p.${q(o.target)} JOIN source.estate_model m ON m.estate_model_pk=d.estate_model_pk WHERE m.publication_state='PUBLISHED') THROW 51003,'PUBLISHED_OWNER_IMMUTABLE',1;`;}
    if(['model.scenario_input','model.scenario_event','model.scenario_outcome'].includes(t.name))published+=` IF EXISTS(SELECT 1 FROM inserted i JOIN model.scenario_version v ON v.scenario_version_pk=i.scenario_version_pk JOIN model.estate_definition d ON d.semantic_object_definition_pk=v.semantic_object_definition_pk JOIN source.estate_model m ON m.estate_model_pk=d.estate_model_pk WHERE m.publication_state='PUBLISHED') THROW 51003,'PUBLISHED_SCENARIO_IMMUTABLE',1;`;
    if(t.name.startsWith('analysis.')&&t.name!=='analysis.assessment'&&t.columns.assessment_pk)published+=` IF EXISTS(SELECT 1 FROM inserted i JOIN analysis.assessment a ON a.assessment_pk=i.assessment_pk JOIN source.estate_model m ON m.estate_model_pk=a.estate_model_pk WHERE m.publication_state='PUBLISHED') THROW 51003,'PUBLISHED_ASSESSMENT_IMMUTABLE',1;`;
    out.push(`CREATE TRIGGER ${q(t.name.split('.')[0])}.${q('guard_'+t.name.split('.')[1])} ON ${fq(t.name)} AFTER INSERT,UPDATE,DELETE AS BEGIN SET NOCOUNT ON; DECLARE @lock int; EXEC @lock=sys.sp_getapplock @Resource='sidefx:model-write',@LockMode='Exclusive',@LockOwner='Transaction',@LockTimeout=60000; IF @lock<0 THROW 51002,'MODEL_LOCK_UNAVAILABLE',1; ${immutable} ${published} END;`);
  }
  out.push(`IF DATABASE_PRINCIPAL_ID('sidefx_reader') IS NULL CREATE USER sidefx_reader WITHOUT LOGIN; IF DATABASE_PRINCIPAL_ID('sidefx_importer') IS NULL CREATE USER sidefx_importer WITHOUT LOGIN; GRANT SELECT ON SCHEMA::sidefx TO sidefx_reader; GRANT SELECT ON SCHEMA::model TO sidefx_reader; GRANT SELECT ON SCHEMA::source TO sidefx_reader; GRANT SELECT ON SCHEMA::analysis TO sidefx_reader; DENY INSERT,UPDATE,DELETE,ALTER ON SCHEMA::model TO sidefx_reader; DENY INSERT,UPDATE,DELETE,ALTER ON SCHEMA::source TO sidefx_reader; DENY INSERT,UPDATE,DELETE,ALTER ON SCHEMA::analysis TO sidefx_reader; DENY ALTER ON SCHEMA::sidefx TO sidefx_reader; GRANT SELECT,INSERT ON SCHEMA::model TO sidefx_importer; GRANT SELECT,INSERT ON SCHEMA::source TO sidefx_importer; GRANT SELECT,INSERT ON SCHEMA::analysis TO sidefx_importer; DENY UPDATE,DELETE,ALTER ON SCHEMA::model TO sidefx_importer; DENY UPDATE,DELETE,ALTER ON SCHEMA::source TO sidefx_importer; DENY UPDATE,DELETE,ALTER ON SCHEMA::analysis TO sidefx_importer; DENY INSERT,UPDATE,DELETE ON OBJECT::source.current_model TO sidefx_importer; GRANT EXECUTE ON OBJECT::source.validate_model TO sidefx_importer; GRANT EXECUTE ON OBJECT::source.publish_model TO sidefx_importer;`);
  // A BUILDING state is the only state an ordinary writer may insert directly.
  out.push(`CREATE TRIGGER source.guard_estate_model ON source.estate_model AFTER INSERT AS BEGIN IF EXISTS(SELECT 1 FROM inserted WHERE publication_state<>'BUILDING') THROW 51003,'MODEL_MUST_START_BUILDING',1; END;`);
  return out;
}
