import {tables,families,q,fq} from './catalog.mjs';

export function viewBatches(){
  const views=new Map();
  const put=(n,s)=>views.set(n,`CREATE VIEW sidefx.${q(n)} AS ${s};`);
  const selected=(alias,column='semantic_object_definition_pk')=>`EXISTS(SELECT 1 FROM model.estate_definition ed JOIN source.current_model cm ON cm.estate_model_pk=ed.estate_model_pk WHERE ed.semantic_object_definition_pk=${alias}.${column})`;
  const cols=(t,a='v')=>Object.keys(tables.get('model.'+t).columns).filter(c=>!c.startsWith('_')).map(c=>`${a}.${q(c)}`).join(',');
  for(const f of families){
    put('v_'+f.version,`SELECT ${cols(f.version)} FROM model.${f.version} v WHERE ${selected('v')}`);
    put('v_'+f.name,`SELECT ${cols(f.name,'i')},(SELECT COUNT_BIG(*) FROM model.${f.version} v WHERE v.${f.name}_pk=i.${f.name}_pk AND ${selected('v')}) definition_count FROM model.${f.name} i WHERE EXISTS(SELECT 1 FROM model.${f.version} v WHERE v.${f.name}_pk=i.${f.name}_pk AND ${selected('v')})`);
  }
  put('v_capability',`SELECT c.capability_pk,c.namespace_pk,c.capability_id,v.capability_version_pk,v.definition_digest,v.name,v.experience_id FROM source.current_model cm JOIN model.estate_capability ec ON ec.estate_model_pk=cm.estate_model_pk JOIN model.capability c ON c.capability_pk=ec.capability_pk JOIN model.capability_version v ON v.capability_version_pk=ec.capability_version_pk`);
  put('v_scenario',`SELECT s.scenario_pk,s.capability_pk,s.scenario_id,v.scenario_version_pk,cs.capability_version_pk,v.definition_digest,v.name,v.source_profile,CONVERT(bit,CASE WHEN i.scenario_version_pk IS NOT NULL THEN 1 ELSE 0 END) has_input,CONVERT(bit,CASE WHEN e.scenario_version_pk IS NOT NULL THEN 1 ELSE 0 END) has_event,CONVERT(bit,CASE WHEN o.scenario_version_pk IS NOT NULL THEN 1 ELSE 0 END) has_outcome,i.contract_reference_state,e.authority_reference_state FROM source.current_model cm JOIN model.estate_capability ec ON ec.estate_model_pk=cm.estate_model_pk JOIN model.capability_scenario cs ON cs.capability_version_pk=ec.capability_version_pk JOIN model.scenario s ON s.scenario_pk=cs.scenario_pk JOIN model.scenario_version v ON v.scenario_version_pk=cs.scenario_version_pk LEFT JOIN model.scenario_input i ON i.scenario_version_pk=v.scenario_version_pk LEFT JOIN model.scenario_event e ON e.scenario_version_pk=v.scenario_version_pk LEFT JOIN model.scenario_outcome o ON o.scenario_version_pk=v.scenario_version_pk`);
  put('v_complete_scenario',`SELECT s.* FROM sidefx.v_scenario s WHERE has_input=1 AND has_event=1 AND has_outcome=1 AND contract_reference_state='RESOLVED' AND authority_reference_state IN('RESOLVED','ABSENT','NOT_APPLICABLE') AND (source_profile NOT LIKE 'scenario-semantic-carrier%' OR EXISTS(SELECT 1 FROM model.outcome_product p WHERE p.scenario_version_pk=s.scenario_version_pk))`);
  for(const n of ['execution_authority','blueprint']){views.delete('v_'+n);put('v_'+n,`SELECT ${cols(n+'_version')} FROM model.${n}_version v WHERE ${selected('v')}`);}
  for(const n of ['execution_operation','blueprint_node','blueprint_edge','provider_slot','outcome_product','outcome_variant_product','outcome_variant','scenario_input','scenario_event','scenario_outcome','port_contract','slot_port_requirement','slot_mechanic_requirement','slot_profile_requirement','fixture','fixture_case','fixture_assertion','observable_condition','proof_obligation'])put('v_'+n,`SELECT ${cols(n)} FROM model.${n} v WHERE ${selected('v','_owner_definition_pk')}`);
  put('v_provider_implementation', ['port','mechanic'].map(target=>`SELECT CAST('${target.toUpperCase()}' AS varchar(64)) implementation_kind,i.provider_${target}_implementation_pk implementation_pk,i.provider_definition_pk,i.${target}_version_pk target_version_pk,i.provider_profile_version_pk,i.role FROM model.provider_${target}_implementation i WHERE ${selected('i','_owner_definition_pk')}`).join(' UNION ALL '));
  put('v_provider_binding',`SELECT b.provider_binding_pk,b.provider_binding_scope_pk,b.provider_slot_pk,b.provider_definition_pk,b.selection_policy,b.ordinal,s.binding_context_pk,s.binding_role,CAST('NOT_EVALUATED' AS varchar(64)) qualification_status,CAST('OUTSIDE_CURRENT_MODEL' AS varchar(64)) runtime_readiness_status FROM model.provider_binding b JOIN model.provider_binding_scope s ON s.provider_binding_scope_pk=b.provider_binding_scope_pk WHERE ${selected('b','_owner_definition_pk')}`);
  put('v_provider_qualification_assessment',`SELECT q.*,a.estate_model_pk,a.evaluation_state,a.scope_digest,a.input_set_digest,a.evaluated_at FROM analysis.provider_qualification_assessment q JOIN analysis.assessment a ON a.assessment_pk=q.assessment_pk JOIN source.current_model cm ON cm.estate_model_pk=a.estate_model_pk`);
  put('v_provider_impact',`SELECT b.provider_definition_pk,cs.capability_version_pk,CAST('CONSUMES' AS varchar(64)) dependency_role,COUNT_BIG(*) path_count FROM source.current_model cm JOIN model.provider_binding b ON ${selected('b','_owner_definition_pk')} JOIN model.provider_slot_operation u ON u.provider_slot_pk=b.provider_slot_pk JOIN model.execution_operation op ON op.execution_operation_pk=u.execution_operation_pk JOIN model.scenario_event e ON e.execution_authority_version_pk=op.execution_authority_version_pk JOIN model.capability_scenario cs ON cs.scenario_version_pk=e.scenario_version_pk JOIN model.estate_capability ec ON ec.estate_model_pk=cm.estate_model_pk AND ec.capability_version_pk=cs.capability_version_pk GROUP BY b.provider_definition_pk,cs.capability_version_pk UNION ALL SELECT i.provider_definition_pk,i.capability_version_pk,CAST('IMPLEMENTS' AS varchar(64)),COUNT_BIG(*) FROM model.provider_capability_implementation i WHERE ${selected('i','_owner_definition_pk')} GROUP BY i.provider_definition_pk,i.capability_version_pk`);
  put('v_product_input_satisfaction',`SELECT c.blueprint_edge_pk,e.blueprint_version_pk,c.product_definition_pk,c.downstream_scenario_version_pk,c.contract_relation,c.compatibility_authority_definition_pk,CASE WHEN a.n=0 THEN 'NOT_EVALUATED' WHEN a.codes>1 THEN 'CONFLICTING_ASSESSMENTS' ELSE a.result END compatibility_status FROM model.blueprint_edge_contract c JOIN model.blueprint_edge e ON e.blueprint_edge_pk=c.blueprint_edge_pk JOIN model.product_definition p ON p.product_definition_pk=c.product_definition_pk JOIN model.scenario_input i ON i.scenario_version_pk=c.downstream_scenario_version_pk OUTER APPLY(SELECT COUNT_BIG(*) n,COUNT(DISTINCT ca.result_code) codes,MIN(ca.result_code) result FROM analysis.compatibility_assessment ca JOIN analysis.assessment a ON a.assessment_pk=ca.assessment_pk JOIN source.current_model cm ON cm.estate_model_pk=a.estate_model_pk WHERE a.evaluation_state='EVALUATED' AND ca.producer_contract_version_pk=p.contract_version_pk AND ca.consumer_contract_version_pk=i.input_contract_version_pk AND ca.authority_definition_pk=c.compatibility_authority_definition_pk) a WHERE ${selected('c','_owner_definition_pk')}`);
  put('v_circuit_cell',`SELECT n.blueprint_version_pk,n.blueprint_node_pk,n.node_id,n.altitude,n.node_kind,f.semantic_object_definition_pk first_definition_pk,f.expected_kind first_kind,e.semantic_object_definition_pk energized_definition_pk,e.expected_kind energized_kind,r.semantic_object_definition_pk result_definition_pk,r.expected_kind result_kind,i.input_contract_version_pk first_contract_version_pk,COALESCE(p.contract_version_pk,oc.contract_version_pk) result_contract_version_pk,CAST('NOT_EVALUATED' AS varchar(64)) semantic_assessment_status,CAST('OUTSIDE_CURRENT_MODEL' AS varchar(64)) runtime_status FROM model.blueprint_node n LEFT JOIN model.blueprint_node_face f ON f.blueprint_node_pk=n.blueprint_node_pk AND f.position='FIRST' LEFT JOIN model.blueprint_node_face e ON e.blueprint_node_pk=n.blueprint_node_pk AND e.position='ENERGIZED' LEFT JOIN model.blueprint_node_face r ON r.blueprint_node_pk=n.blueprint_node_pk AND r.position='RESULT' LEFT JOIN model.scenario_input i ON i.semantic_object_definition_pk=f.semantic_object_definition_pk LEFT JOIN model.product_definition p ON p.semantic_object_definition_pk=r.semantic_object_definition_pk LEFT JOIN model.scenario_outcome o ON o.semantic_object_definition_pk=r.semantic_object_definition_pk LEFT JOIN model.scenario_outcome_contract oc ON oc.scenario_version_pk=o.scenario_version_pk WHERE ${selected('n','_owner_definition_pk')}`);
  put('v_circuit_route',`SELECT * FROM sidefx.v_blueprint_edge`);
  put('v_circuit_integrity_findings',`SELECT f.*,a.estate_model_pk,a.integrity_rule_pk,r.layer,c.blueprint_version_pk,c.blueprint_node_pk FROM analysis.integrity_finding f JOIN analysis.assessment a ON a.assessment_pk=f.assessment_pk JOIN analysis.integrity_rule r ON r.integrity_rule_pk=a.integrity_rule_pk JOIN source.current_model cm ON cm.estate_model_pk=a.estate_model_pk LEFT JOIN analysis.circuit_assessment c ON c.assessment_pk=a.assessment_pk WHERE a.assessment_kind IN('CIRCUIT','INTEGRITY')`);
  put('v_estate_inventory',`SELECT a.source_appearance_pk,a.source_path,a.source_class,a.content_object_pk,c.family_code,c.classification_state,c.mapping_rule_pk FROM source.current_model cm JOIN source.estate_model m ON m.estate_model_pk=cm.estate_model_pk JOIN source.source_appearance a ON a.estate_snapshot_pk=m.estate_snapshot_pk LEFT JOIN source.source_classification c ON c.source_appearance_pk=a.source_appearance_pk AND EXISTS(SELECT 1 FROM source.estate_model_rule mr WHERE mr.estate_model_pk=m.estate_model_pk AND mr.mapping_rule_pk=c.mapping_rule_pk)`);
  put('v_definition_lineage',`SELECT l.source_lineage_pk,l.semantic_object_definition_pk,l.member_kind,l.canonical_pointer,l.mapping_rule_pk,l.contribution_role,o.source_observation_pk,o.locator,a.source_path,a.source_class,a.capsule_digest,a.referenced_authority_digest FROM source.current_model cm JOIN source.estate_model m ON m.estate_model_pk=cm.estate_model_pk JOIN source.source_lineage l ON ${selected('l')} JOIN source.source_observation o ON o.source_observation_pk=l.source_observation_pk JOIN source.source_appearance a ON a.source_appearance_pk=o.source_appearance_pk AND a.estate_snapshot_pk=m.estate_snapshot_pk WHERE EXISTS(SELECT 1 FROM source.estate_model_rule r WHERE r.estate_model_pk=m.estate_model_pk AND r.mapping_rule_pk=l.mapping_rule_pk)`);
  put('v_assessment_coverage',`SELECT c.*,a.estate_model_pk,a.evaluation_state FROM analysis.coverage_assessment c JOIN analysis.assessment a ON a.assessment_pk=c.assessment_pk JOIN source.current_model cm ON cm.estate_model_pk=a.estate_model_pk`);
  put('v_version_label',`SELECT l.semantic_object_pk,l.version_label,l.semantic_object_definition_pk,l.definition_digest FROM model.definition_version_label l WHERE ${selected('l')}`);
  return [...views.values()];
}
